// مكتبة المصادر العلمية الموثّقة لمنصة دامج
// كل مصدر يحتوي على: العنوان، المؤلفون/الجهة، السنة، الرابط، الفئة،
// أين استُخدم في المنصة، وشرح موجز.

export interface ScientificSource {
  id: string;
  title: string;
  authors: string;
  year: string;
  url: string;
  category: SourceCategory;
  usedIn: string;       // أين استُخدم في المنصة
  note: string;         // شرح موجز
  type: 'guideline' | 'research' | 'book' | 'standard' | 'tool' | 'dataset' | 'model';
}

export type SourceCategory =
  | 'autism-diagnosis'
  | 'autism-therapy'
  | 'adhd-diagnosis'
  | 'adhd-therapy'
  | 'blind-vision'
  | 'braille'
  | 'sign-language'
  | 'sensory'
  | 'clinical-ai'
  | 'inclusive-edu'
  | 'speech-audio'
  | 'navigation-geo'
  | 'ai-foundations';

export const CATEGORY_LABELS: Record<SourceCategory, string> = {
  'autism-diagnosis': 'تشخيص التوحّد وفحصه',
  'autism-therapy': 'تدخّل وعلاج التوحّد',
  'adhd-diagnosis': 'تشخيص ADHD',
  'adhd-therapy': 'تدخّل وعلاج ADHD',
  'blind-vision': 'الإعاقة البصرية والرؤية الحاسوبية',
  'braille': 'بريل ومعايير القراءة اللمسية',
  'sign-language': 'لغة الإشارة والصمم',
  'sensory': 'المعالجة الحسية',
  'clinical-ai': 'الطب السريري والذكاء الصناعي الطبي',
  'inclusive-edu': 'التعليم الدامج والسياسات',
  'speech-audio': 'الكلام والصوت والـ TTS/STT',
  'navigation-geo': 'الملاحة والخرائط والاستشعار',
  'ai-foundations': 'أسس الذكاء الصناعي ورؤية الحاسوب',
};

export const SOURCES: ScientificSource[] = [
  // ============================================================
  // 1) AUTISM — DIAGNOSIS & SCREENING (28)
  // ============================================================
  { id: 'dsm5tr', title: 'DSM-5-TR — Diagnostic and Statistical Manual of Mental Disorders', authors: 'American Psychiatric Association', year: '2022', url: 'https://www.psychiatry.org/psychiatrists/practice/dsm', category: 'autism-diagnosis', type: 'guideline',
    usedIn: 'محرّك التقييم في قسم التوحّد · تقرير DSM dimensions',
    note: 'المرجع التشخيصي المعتمد عالمياً لاضطراب طيف التوحّد (المعيار A: التواصل الاجتماعي، B: السلوك المقيّد/المتكرر، الحساسية الحسية، مستويات الدعم 1–3).' },
  { id: 'mchat-rf', title: 'M-CHAT-R/F — Modified Checklist for Autism in Toddlers, Revised with Follow-Up', authors: 'Robins, Fein & Barton', year: '2014', url: 'https://mchatscreen.com/', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'بنود فحص الأطفال 16–30 شهر في AutismChildPage',
    note: 'أداة الفحص الأولي الأكثر استخداماً عالمياً لرصد مؤشرات التوحّد المبكرة.' },
  { id: 'ados2', title: 'ADOS-2 — Autism Diagnostic Observation Schedule, Second Edition', authors: 'Lord, Rutter, DiLavore et al.', year: '2012', url: 'https://www.wpspublish.com/ados-2', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'بنود الملاحظة السلوكية في الألعاب التشخيصية (Joint Attention، Response to Name)',
    note: 'المعيار الذهبي لتشخيص التوحّد بالملاحظة المباشرة.' },
  { id: 'adir', title: 'ADI-R — Autism Diagnostic Interview, Revised', authors: 'Le Couteur, Lord & Rutter', year: '2003', url: 'https://www.wpspublish.com/adi-r-autism-diagnostic-interview-revised', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'صياغة أسئلة المقابلة مع ولي الأمر',
    note: 'مقابلة شبه منظمة مع الوالدين لتأكيد التشخيص.' },
  { id: 'cars2', title: 'CARS-2 — Childhood Autism Rating Scale, Second Edition', authors: 'Schopler, Van Bourgondien et al.', year: '2010', url: 'https://www.wpspublish.com/cars-2', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'تصنيف شدة المؤشرات في تقرير التوحّد',
    note: 'مقياس مكوّن من 15 بنداً لتقدير شدة طيف التوحّد.' },
  { id: 'srs2', title: 'SRS-2 — Social Responsiveness Scale, Second Edition', authors: 'Constantino & Gruber', year: '2012', url: 'https://www.wpspublish.com/srs-2', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'حساب درجة التواصل الاجتماعي domain_score',
    note: 'يقيس شدة الأعراض الاجتماعية في 65 بنداً.' },
  { id: 'gars3', title: 'GARS-3 — Gilliam Autism Rating Scale', authors: 'Gilliam', year: '2013', url: 'https://www.proedinc.com/Products/13660/gars3-gilliam-autism-rating-scalethird-edition.aspx', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'مقاطع التقييم العمري المتكيّف',
    note: 'تقدير احتمال التوحّد للأعمار 3–22 سنة.' },
  { id: 'cdc-asd-hcp', title: 'CDC — Diagnosis of ASD (Healthcare Providers)', authors: 'Centers for Disease Control and Prevention', year: '2024', url: 'https://www.cdc.gov/autism/hcp/diagnosis/index.html', category: 'autism-diagnosis', type: 'guideline',
    usedIn: 'إخلاء المسؤولية SCREENING_DISCLAIMER_AR',
    note: 'إرشادات CDC لمقدّمي الرعاية الصحية حول تشخيص طيف التوحّد.' },
  { id: 'cdc-asd-screening', title: 'CDC — Clinical Screening for ASD', authors: 'CDC', year: '2024', url: 'https://www.cdc.gov/autism/hcp/screening/index.html', category: 'autism-diagnosis', type: 'guideline',
    usedIn: 'سياسة عرض النتائج بثلاث فئات (low/monitor/refer)',
    note: 'بروتوكول الفحص السريري قبل الإحالة.' },
  { id: 'cdc-asd-diagnosis', title: 'CDC — How is Autism Diagnosed?', authors: 'CDC', year: '2024', url: 'https://www.cdc.gov/autism/diagnosis/index.html', category: 'autism-diagnosis', type: 'guideline',
    usedIn: 'صياغة summary_ar وقسم next_steps',
    note: 'دليل تشخيص التوحّد الموجّه للأسر.' },
  { id: 'aap-asd-2020', title: 'AAP — Identification, Evaluation, and Management of Children With ASD', authors: 'Hyman, Levy, Myers et al.', year: '2020', url: 'https://publications.aap.org/pediatrics/article/145/1/e20193447/36917', category: 'autism-diagnosis', type: 'guideline',
    usedIn: 'هيكل تقرير referral_priority',
    note: 'إرشادات الأكاديمية الأمريكية لطب الأطفال للتشخيص والإدارة.' },
  { id: 'nice-cg128', title: 'NICE CG128 — Autism diagnosis in under 19s', authors: 'NICE UK', year: '2017', url: 'https://www.nice.org.uk/guidance/cg128', category: 'autism-diagnosis', type: 'guideline',
    usedIn: 'مسار الإحالة في تقرير التوحّد',
    note: 'إرشادات بريطانيا لتشخيص التوحّد للأطفال.' },
  { id: 'nice-cg170', title: 'NICE CG170 — ASD in under 19s: support and management', authors: 'NICE UK', year: '2013', url: 'https://www.nice.org.uk/guidance/cg170', category: 'autism-diagnosis', type: 'guideline',
    usedIn: 'تحديد recommended_game_tracks',
    note: 'إدارة ودعم الأطفال على طيف التوحّد.' },
  { id: 'who-asd-fact', title: 'WHO — Autism Fact Sheet', authors: 'World Health Organization', year: '2023', url: 'https://www.who.int/news-room/fact-sheets/detail/autism-spectrum-disorders', category: 'autism-diagnosis', type: 'guideline',
    usedIn: 'القسم التعريفي في صفحة AutismHome',
    note: 'تعريف عالمي وانتشار وإحصائيات التوحّد.' },
  { id: 'autism-cdc-treatment', title: 'CDC — Treatment and Intervention for ASD', authors: 'CDC', year: '2024', url: 'https://www.cdc.gov/autism/treatment/index.html', category: 'autism-therapy', type: 'guideline',
    usedIn: 'أنواع المسارات في AutismTherapyPlan',
    note: 'أنواع التدخلات المعتمدة (سلوكية، تطورية، تعليمية).' },
  { id: 'who-cst', title: 'WHO — Caregiver Skills Training for ASD', authors: 'WHO', year: '2022', url: 'https://www.who.int/teams/mental-health-and-substance-use/policy-law-rights/caregiver-skills-training', category: 'autism-therapy', type: 'guideline',
    usedIn: 'بنود parent_actions في التقرير',
    note: 'برنامج عالمي لتدريب الأسر على دعم أطفال التوحّد.' },
  { id: 'baird-2006', title: 'Prevalence of disorders of the autism spectrum in a population cohort', authors: 'Baird et al.', year: '2006', url: 'https://pubmed.ncbi.nlm.nih.gov/16844490/', category: 'autism-diagnosis', type: 'research',
    usedIn: 'مرجع إحصاءات الانتشار في الواجهة',
    note: 'دراسة وبائية أساسية لقياس انتشار التوحّد.' },
  { id: 'mottron-strengths', title: 'Enhanced perceptual functioning in autism', authors: 'Mottron, Dawson, Soulières et al.', year: '2006', url: 'https://link.springer.com/article/10.1007/s10803-005-0040-7', category: 'autism-diagnosis', type: 'research',
    usedIn: 'قسم strengths في التقرير',
    note: 'نظرية القدرات الإدراكية المتفوّقة لدى أطفال التوحّد.' },
  { id: 'happe-frith-wcc', title: 'Weak central coherence theory', authors: 'Happé & Frith', year: '2006', url: 'https://link.springer.com/article/10.1007/s10803-005-0039-0', category: 'autism-diagnosis', type: 'research',
    usedIn: 'تفسير نمط RepetitiveMatch',
    note: 'نظرية ضعف الترابط المركزي في التوحّد.' },
  { id: 'baron-cohen-eyes', title: 'The "Reading the Mind in the Eyes" Test', authors: 'Baron-Cohen et al.', year: '2001', url: 'https://docs.autismresearchcentre.com/papers/2001_BCetal_adulteyes.pdf', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'تصميم لعبة EmotionRecognition',
    note: 'يقيس نظرية العقل من خلال تمييز المشاعر بالعينين.' },
  { id: 'mundy-jat', title: 'Joint attention, social cognition, and autism', authors: 'Mundy & Newell', year: '2007', url: 'https://journals.sagepub.com/doi/10.1111/j.1467-8721.2007.00518.x', category: 'autism-diagnosis', type: 'research',
    usedIn: 'لعبة JointAttention',
    note: 'الانتباه المشترك مؤشر أساسي مبكر للتوحّد.' },
  { id: 'response-to-name', title: 'Failure to respond to name: marker for early ASD', authors: 'Nadig et al.', year: '2007', url: 'https://pubmed.ncbi.nlm.nih.gov/17404140/', category: 'autism-diagnosis', type: 'research',
    usedIn: 'لعبة ResponseToName',
    note: 'عدم الاستجابة للاسم مؤشر مبكر قوي.' },
  { id: 'rrb-bodfish', title: 'Repetitive Behavior Scale-Revised (RBS-R)', authors: 'Bodfish et al.', year: '2000', url: 'https://pubmed.ncbi.nlm.nih.gov/11055457/', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'حساب درجة restricted_repetitive',
    note: 'مقياس السلوكيات المقيّدة والمتكررة.' },
  { id: 'ssp-dunn', title: 'Sensory Profile (Dunn)', authors: 'Winnie Dunn', year: '1999', url: 'https://www.pearsonassessments.com/store/usassessments/en/Store/Professional-Assessments/Behavior/Sensory-Profile-2/p/100000822.html', category: 'autism-diagnosis', type: 'tool',
    usedIn: 'لعبة SensoryTolerance ومقياس sensory',
    note: 'يقيس أنماط المعالجة الحسية لدى الأطفال.' },
  { id: 'eserap', title: 'Early Start Denver Model — Rogers & Dawson', authors: 'Rogers & Dawson', year: '2010', url: 'https://www.guilford.com/books/Early-Start-Denver-Model-for-Young-Children-with-Autism/Rogers-Dawson/9781606236321', category: 'autism-therapy', type: 'book',
    usedIn: 'مسار العلاج المبكر في AutismTherapy',
    note: 'نموذج تدخّل سلوكي–تطوّري مبكّر مدعوم بالأبحاث.' },
  { id: 'aba-cooper', title: 'Applied Behavior Analysis (3rd ed.)', authors: 'Cooper, Heron & Heward', year: '2020', url: 'https://www.pearson.com/en-us/subject-catalog/p/applied-behavior-analysis/P200000003415', category: 'autism-therapy', type: 'book',
    usedIn: 'تصميم نظام التعزيز في الألعاب',
    note: 'الكتاب المرجعي لتحليل السلوك التطبيقي.' },
  { id: 'pivotal-koegel', title: 'Pivotal Response Treatment (PRT)', authors: 'Koegel & Koegel', year: '2006', url: 'https://www.brookespublishing.com/product/pivotal-response-treatments-for-autism/', category: 'autism-therapy', type: 'book',
    usedIn: 'مسار التواصل في الخطة العلاجية',
    note: 'علاج محوري لاستجابات اللعب والتواصل.' },
  { id: 'teacch', title: 'TEACCH Approach to ASD', authors: 'Mesibov, Shea & Schopler', year: '2004', url: 'https://link.springer.com/book/10.1007/978-0-306-48647-0', category: 'autism-therapy', type: 'book',
    usedIn: 'هيكل البيئات البصرية والروتين في AutismDayView',
    note: 'تدخّل قائم على البنية البصرية والروتين.' },

  // ============================================================
  // 2) AUTISM THERAPY (15)
  // ============================================================
  { id: 'pecs-bondy', title: 'Picture Exchange Communication System (PECS)', authors: 'Bondy & Frost', year: '2001', url: 'https://pecsusa.com/', category: 'autism-therapy', type: 'tool',
    usedIn: 'بطاقات التواصل في AutismProgramSetup',
    note: 'نظام تواصل بديل بالصور للأطفال غير الناطقين.' },
  { id: 'floortime', title: 'DIR/Floortime Model', authors: 'Greenspan & Wieder', year: '2006', url: 'https://www.icdl.com/dir', category: 'autism-therapy', type: 'book',
    usedIn: 'أنشطة اللعب التفاعلي في AutismGamePlayer',
    note: 'نموذج تطوّري عبر اللعب التفاعلي.' },
  { id: 'social-stories', title: 'Social Stories — Carol Gray', authors: 'Carol Gray', year: '2015', url: 'https://carolgraysocialstories.com/', category: 'autism-therapy', type: 'tool',
    usedIn: 'سيناريوهات اجتماعية في الألعاب',
    note: 'قصص قصيرة لتعليم المهارات الاجتماعية.' },
  { id: 'visual-schedules', title: 'Visual Supports for ASD — National Autism Center', authors: 'NAC', year: '2015', url: 'https://www.nationalautismcenter.org/', category: 'autism-therapy', type: 'guideline',
    usedIn: 'الجدول البصري اليومي AutismDayView',
    note: 'مرجع للجداول البصرية والدعم البصري.' },
  { id: 'jasper', title: 'JASPER — Joint Attention, Symbolic Play, Engagement and Regulation', authors: 'Kasari et al.', year: '2014', url: 'https://www.semel.ucla.edu/autism/jasper-training', category: 'autism-therapy', type: 'research',
    usedIn: 'لعبة JointAttention المتقدمة',
    note: 'تدخّل مدعوم تجريبياً للانتباه المشترك واللعب الرمزي.' },
  { id: 'nac-ebp-2015', title: 'National Standards Project, Phase 2', authors: 'National Autism Center', year: '2015', url: 'https://www.nationalautismcenter.org/national-standards/', category: 'autism-therapy', type: 'guideline',
    usedIn: 'تصنيف التدخلات حسب القوة العلمية',
    note: 'تصنيف التدخلات السلوكية المدعومة بأدلة.' },
  { id: 'ndbi', title: 'Naturalistic Developmental Behavioral Interventions', authors: 'Schreibman et al.', year: '2015', url: 'https://link.springer.com/article/10.1007/s10803-015-2407-8', category: 'autism-therapy', type: 'research',
    usedIn: 'إطار التدخلات الطبيعية في AutismTherapyPlan',
    note: 'دمج المبادئ السلوكية مع التطوّر الطبيعي.' },
  { id: 'speech-aac', title: 'Augmentative and Alternative Communication (AAC)', authors: 'Beukelman & Light', year: '2020', url: 'https://www.brookespublishing.com/product/augmentative-alternative-communication/', category: 'autism-therapy', type: 'book',
    usedIn: 'لوحات التواصل البديلة',
    note: 'الكتاب المرجعي للتواصل المعزَّز والبديل.' },
  { id: 'fct-carr', title: 'Functional Communication Training', authors: 'Carr & Durand', year: '1985', url: 'https://pubmed.ncbi.nlm.nih.gov/3998937/', category: 'autism-therapy', type: 'research',
    usedIn: 'مسار خفض السلوكيات التحدّوية',
    note: 'تدريب التواصل الوظيفي بدلاً من السلوكيات الصعبة.' },
  { id: 'jaspr-prediction', title: 'Predictors of Outcomes in Autism Intervention', authors: 'Vivanti & Dissanayake', year: '2016', url: 'https://link.springer.com/article/10.1007/s10803-016-2777-6', category: 'autism-therapy', type: 'research',
    usedIn: 'حساب confidence_score',
    note: 'يدرس العوامل المتنبئة بنجاح التدخّل المبكّر.' },
  { id: 'parents-prt', title: 'Parent-Mediated PRT', authors: 'Hardan et al.', year: '2015', url: 'https://pubmed.ncbi.nlm.nih.gov/25865493/', category: 'autism-therapy', type: 'research',
    usedIn: 'بنود parent_actions',
    note: 'فعالية تدريب الوالدين كوسيط علاجي.' },
  { id: 'sensory-integration-ayres', title: 'Sensory Integration and the Child', authors: 'A. Jean Ayres', year: '2005', url: 'https://www.wpspublish.com/sensory-integration-and-the-child-25th-anniversary-edition', category: 'sensory', type: 'book',
    usedIn: 'إعدادات SensoryProfileSetup',
    note: 'الكتاب المؤسس لنظرية التكامل الحسي.' },
  { id: 'occupational-therapy-asd', title: 'Occupational Therapy for ASD — AOTA', authors: 'American Occupational Therapy Association', year: '2020', url: 'https://www.aota.org/practice/clinical-topics/autism', category: 'autism-therapy', type: 'guideline',
    usedIn: 'توصيات OT في التقرير',
    note: 'إرشادات العلاج الوظيفي لأطفال التوحّد.' },
  { id: 'speech-asha-asd', title: 'ASHA Practice Portal — Autism', authors: 'American Speech-Language-Hearing Association', year: '2024', url: 'https://www.asha.org/practice-portal/clinical-topics/autism/', category: 'autism-therapy', type: 'guideline',
    usedIn: 'مسار اللغة في AutismTherapyPlan',
    note: 'مرجع علاج اللغة والكلام للتوحّد.' },
  { id: 'autism-meds-aacap', title: 'AACAP Practice Parameter for ASD', authors: 'AACAP', year: '2014', url: 'https://www.jaacap.org/article/S0890-8567(13)00819-8/fulltext', category: 'autism-therapy', type: 'guideline',
    usedIn: 'تنبيهات الإحالة الدوائية',
    note: 'إرشادات الطب النفسي للأطفال في إدارة التوحّد.' },

  // ============================================================
  // 3) ADHD DIAGNOSIS (15)
  // ============================================================
  { id: 'nichq-vanderbilt', title: 'NICHQ Vanderbilt Assessment Scales', authors: 'Wolraich, NICHQ', year: '2002', url: 'https://www.nichq.org/sites/default/files/resource-file/NICHQ_Vanderbilt_Assessment_Scales.pdf', category: 'adhd-diagnosis', type: 'tool',
    usedIn: 'بنود تقييم الوالدين والمعلم في ADHD screening',
    note: 'مقياس فاندربيلت معتمد من AAP للأطفال 6–12.' },
  { id: 'asrs-who', title: 'WHO ASRS-v1.1 — Adult ADHD Self-Report Scale', authors: 'Kessler / WHO', year: '2005', url: 'https://add.org/wp-content/uploads/2015/03/adhd-questionnaire-ASRS111.pdf', category: 'adhd-diagnosis', type: 'tool',
    usedIn: 'فحص ADHD البالغين',
    note: 'استبيان عالمي لفحص ADHD لدى البالغين.' },
  { id: 'snap-iv', title: 'SNAP-IV 26 Scoring Guide', authors: 'Swanson, Nolan, Pelham', year: '2008', url: 'https://www.shared-care.ca/files/Scoring_for_SNAP_IV_Guide_26-item.pdf', category: 'adhd-diagnosis', type: 'tool',
    usedIn: 'حساب الأبعاد الفرعية لـ ADHD',
    note: 'مقياس SNAP لتقدير الانتباه/فرط النشاط.' },
  { id: 'aap-adhd-2019', title: 'AAP Clinical Practice Guideline for ADHD', authors: 'Wolraich et al.', year: '2019', url: 'https://publications.aap.org/pediatrics/article/144/4/e20192528', category: 'adhd-diagnosis', type: 'guideline',
    usedIn: 'بروتوكول مرحلة التقييم في ADHD',
    note: 'إرشادات AAP المعتمدة لتشخيص وعلاج ADHD.' },
  { id: 'nice-ng87', title: 'NICE NG87 — ADHD diagnosis and management', authors: 'NICE UK', year: '2019', url: 'https://www.nice.org.uk/guidance/ng87', category: 'adhd-diagnosis', type: 'guideline',
    usedIn: 'مسار الإحالة الدوائية',
    note: 'إرشادات بريطانية شاملة لإدارة ADHD.' },
  { id: 'cdc-adhd', title: 'CDC — ADHD', authors: 'CDC', year: '2024', url: 'https://www.cdc.gov/adhd/', category: 'adhd-diagnosis', type: 'guideline',
    usedIn: 'المحتوى التثقيفي في ADHDHome',
    note: 'بوابة CDC لاضطراب فرط الحركة وتشتت الانتباه.' },
  { id: 'conners3', title: 'Conners-3 — Conners Comprehensive Behavior Rating Scales', authors: 'Conners', year: '2008', url: 'https://www.mhs.com/MHS-Assessment?prodname=conners3', category: 'adhd-diagnosis', type: 'tool',
    usedIn: 'بنود فحص الأطفال والمراهقين',
    note: 'مقياس Conners-3 لتقييم ADHD ومشكلات السلوك.' },
  { id: 'cpt3', title: 'Conners CPT-3 — Continuous Performance Test', authors: 'Conners', year: '2014', url: 'https://www.mhs.com/MHS-Assessment?prodname=cpt3', category: 'adhd-diagnosis', type: 'tool',
    usedIn: 'لعبة الانتباه المستمرّ في ADHDGameEngine',
    note: 'اختبار حاسوبي للانتباه المستمرّ والاندفاعية.' },
  { id: 'tova', title: 'TOVA — Test of Variables of Attention', authors: 'Greenberg', year: '1996', url: 'https://www.tovatest.com/', category: 'adhd-diagnosis', type: 'tool',
    usedIn: 'محرّك ألعاب الانتباه',
    note: 'اختبار TOVA لقياس الانتباه بصرياً وسمعياً.' },
  { id: 'stroop-1935', title: 'Studies of interference in serial verbal reactions', authors: 'Stroop', year: '1935', url: 'https://psychclassics.yorku.ca/Stroop/', category: 'adhd-diagnosis', type: 'research',
    usedIn: 'لعبة Stroop في ألعاب ADHD',
    note: 'المقال الأصلي لتأثير سترووب على الكفّ المعرفي.' },
  { id: 'nback-kirchner', title: 'Age differences in short-term retention (N-Back)', authors: 'Kirchner', year: '1958', url: 'https://psycnet.apa.org/record/1959-06769-001', category: 'adhd-diagnosis', type: 'research',
    usedIn: 'لعبة N-Back للذاكرة العاملة',
    note: 'مهمة N-Back الأصلية لذاكرة العمل.' },
  { id: 'jaeggi-wm', title: 'Improving fluid intelligence with WM training', authors: 'Jaeggi et al.', year: '2008', url: 'https://www.pnas.org/doi/10.1073/pnas.0801268105', category: 'adhd-therapy', type: 'research',
    usedIn: 'تصميم التدرّج في تدريبات الذاكرة العاملة',
    note: 'تدريب ذاكرة العمل يحسّن الذكاء المرن.' },
  { id: 'gonogo-newman', title: 'Passive avoidance learning (Go/No-Go)', authors: 'Newman, Patterson & Kosson', year: '1985', url: 'https://pubmed.ncbi.nlm.nih.gov/4031228/', category: 'adhd-diagnosis', type: 'research',
    usedIn: 'لعبة Go/No-Go للكفّ الاستجابي',
    note: 'بروتوكول Go/No-Go للكفّ السلوكي.' },
  { id: 'bbcs-ekman', title: 'Stop-Signal Task', authors: 'Logan & Cowan', year: '1984', url: 'https://psycnet.apa.org/doi/10.1037/0033-295X.91.3.295', category: 'adhd-diagnosis', type: 'research',
    usedIn: 'لعبة Stop-Signal',
    note: 'نظرية إشارة التوقّف لقياس الكفّ.' },
  { id: 'wisc-v', title: 'WISC-V — Wechsler Intelligence Scale for Children', authors: 'Wechsler', year: '2014', url: 'https://www.pearsonassessments.com/store/usassessments/en/Store/Professional-Assessments/Cognition-%26-Neuro/Wechsler-Intelligence-Scale-for-Children-%7C-Fifth-Edition/p/100000771.html', category: 'adhd-diagnosis', type: 'tool',
    usedIn: 'مرجع تقدير قدرات الذاكرة وسرعة المعالجة',
    note: 'مقياس ذكاء الأطفال المعتمد دولياً.' },

  // ============================================================
  // 4) ADHD THERAPY (15)
  // ============================================================
  { id: 'barkley-book', title: 'Taking Charge of ADHD', authors: 'Russell A. Barkley', year: '2020', url: 'https://www.guilford.com/books/Taking-Charge-of-ADHD/Russell-Barkley/9781462542673', category: 'adhd-therapy', type: 'book',
    usedIn: 'محتوى ADHDResources وبنود parent_actions',
    note: 'الكتاب المرجعي للأهل في إدارة ADHD.' },
  { id: 'chadd', title: 'CHADD — Children and Adults with ADHD', authors: 'CHADD', year: '2024', url: 'https://chadd.org/', category: 'adhd-therapy', type: 'guideline',
    usedIn: 'موارد الأسر في ADHDResources',
    note: 'منظمة وطنية أمريكية للدعم والتثقيف حول ADHD.' },
  { id: 'pbt-pelham', title: 'Behavioral Parent Training', authors: 'Pelham & Fabiano', year: '2008', url: 'https://pubmed.ncbi.nlm.nih.gov/18444058/', category: 'adhd-therapy', type: 'research',
    usedIn: 'مسار تدريب الوالدين',
    note: 'تدريب الوالدين السلوكي علاج أولي لـ ADHD.' },
  { id: 'cbt-safren', title: 'CBT for Adult ADHD', authors: 'Safren et al.', year: '2010', url: 'https://pubmed.ncbi.nlm.nih.gov/20682365/', category: 'adhd-therapy', type: 'research',
    usedIn: 'مسار العلاج المعرفي للبالغين',
    note: 'علاج معرفي–سلوكي لبالغي ADHD.' },
  { id: 'organizational-skills', title: 'Organizational Skills Training', authors: 'Abikoff et al.', year: '2013', url: 'https://pubmed.ncbi.nlm.nih.gov/23106896/', category: 'adhd-therapy', type: 'research',
    usedIn: 'تدريبات التنظيم في ADHD',
    note: 'تدريب مهارات التنظيم للأطفال.' },
  { id: 'mta-study', title: 'MTA Cooperative Group Study', authors: 'NIMH MTA', year: '1999', url: 'https://pubmed.ncbi.nlm.nih.gov/10591283/', category: 'adhd-therapy', type: 'research',
    usedIn: 'مقارنة فعالية المسارات في التقارير',
    note: 'دراسة طويلة الأمد قارنت العلاجات الدوائية والسلوكية.' },
  { id: 'efs-dawson', title: 'Smart but Scattered (Executive Functions)', authors: 'Dawson & Guare', year: '2018', url: 'https://www.guilford.com/books/Smart-but-Scattered/Peg-Dawson-Richard-Guare/9781462536160', category: 'adhd-therapy', type: 'book',
    usedIn: 'مسار الوظائف التنفيذية',
    note: 'دليل تطوير الوظائف التنفيذية لدى الأطفال.' },
  { id: 'mindfulness-zylowska', title: 'Mindfulness Meditation Training in Adults & Adolescents with ADHD', authors: 'Zylowska et al.', year: '2008', url: 'https://pubmed.ncbi.nlm.nih.gov/18025249/', category: 'adhd-therapy', type: 'research',
    usedIn: 'مسار اليقظة الذهنية',
    note: 'فعالية اليقظة الذهنية لتحسين الانتباه.' },
  { id: 'neurofeedback-arns', title: 'EEG Neurofeedback for ADHD: meta-analysis', authors: 'Arns et al.', year: '2014', url: 'https://pubmed.ncbi.nlm.nih.gov/24077054/', category: 'adhd-therapy', type: 'research',
    usedIn: 'مرجع تحليلي للمسار العصبي',
    note: 'تقييم فعالية التدريب العصبي.' },
  { id: 'gamification-bavelier', title: 'Brains on video games', authors: 'Bavelier et al.', year: '2011', url: 'https://www.nature.com/articles/nrn3135', category: 'adhd-therapy', type: 'research',
    usedIn: 'تصميم الألعاب التدريبية',
    note: 'أساس علمي لاستخدام الألعاب في تدريب الانتباه.' },
  { id: 'endeavor-rx', title: 'EndeavorRx — FDA-cleared digital therapeutic', authors: 'Akili Interactive', year: '2020', url: 'https://www.akiliinteractive.com/', category: 'adhd-therapy', type: 'tool',
    usedIn: 'مرجع تصميم ألعاب علاجية رقمية',
    note: 'أوّل لعبة علاجية معتمدة من FDA لـ ADHD.' },
  { id: 'reward-dopamine-volkow', title: 'Evaluating dopamine reward pathway in ADHD', authors: 'Volkow et al.', year: '2009', url: 'https://pubmed.ncbi.nlm.nih.gov/19738093/', category: 'adhd-therapy', type: 'research',
    usedIn: 'نظام التعزيز في الألعاب',
    note: 'مسار الدوبامين والمكافأة في ADHD.' },
  { id: 'sleep-cortese', title: 'Sleep in children with ADHD: meta-analysis', authors: 'Cortese et al.', year: '2009', url: 'https://pubmed.ncbi.nlm.nih.gov/19264967/', category: 'adhd-therapy', type: 'research',
    usedIn: 'بنود نمط الحياة في التقرير',
    note: 'أثر النوم على أعراض ADHD.' },
  { id: 'omega3-bloch', title: 'Omega-3 for ADHD: meta-analysis', authors: 'Bloch & Qawasmi', year: '2011', url: 'https://pubmed.ncbi.nlm.nih.gov/21961774/', category: 'adhd-therapy', type: 'research',
    usedIn: 'توصيات تغذوية تكميلية',
    note: 'مراجعة فعالية أوميغا-3 في ADHD.' },
  { id: 'school-accommodations', title: '504/IEP School Accommodations for ADHD', authors: 'US Dept of Education', year: '2016', url: 'https://www2.ed.gov/about/offices/list/ocr/letters/colleague-201607-504-adhd.pdf', category: 'adhd-therapy', type: 'guideline',
    usedIn: 'بنود التوصيات المدرسية',
    note: 'دليل التسهيلات المدرسية لطلبة ADHD.' },

  // ============================================================
  // 5) BLIND / VISION / NAVIGATION (28)
  // ============================================================
  { id: 'yolov8', title: 'YOLOv8 — Real-Time Object Detection', authors: 'Ultralytics', year: '2023', url: 'https://docs.ultralytics.com/', category: 'blind-vision', type: 'model',
    usedIn: 'كشف الأجسام في عين الأعمى (BlindEyeNavigator)',
    note: 'محرّك كشف الأجسام السريع للأبواب والكراسي والأشخاص.' },
  { id: 'yolo-original', title: 'You Only Look Once: Unified Real-Time Object Detection', authors: 'Redmon et al.', year: '2016', url: 'https://arxiv.org/abs/1506.02640', category: 'blind-vision', type: 'research',
    usedIn: 'الأساس النظري لـ YOLO المستخدم',
    note: 'الورقة الأصلية لمنهجية YOLO للكشف الفوري.' },
  { id: 'coco-dataset', title: 'Microsoft COCO: Common Objects in Context', authors: 'Lin et al.', year: '2014', url: 'https://arxiv.org/abs/1405.0312', category: 'blind-vision', type: 'dataset',
    usedIn: 'تصنيفات الأجسام المستخدمة في YOLO',
    note: 'مجموعة بيانات الأجسام الأشهر عالمياً.' },
  { id: 'midas', title: 'MiDaS — Towards Robust Monocular Depth Estimation', authors: 'Ranftl et al.', year: '2020', url: 'https://arxiv.org/abs/1907.01341', category: 'blind-vision', type: 'model',
    usedIn: 'تقدير المسافة في عين الأعمى',
    note: 'تقدير العمق من كاميرا واحدة بدون مستشعر إضافي.' },
  { id: 'dpt-depth', title: 'Dense Prediction Transformers (DPT)', authors: 'Ranftl, Bochkovskiy & Koltun', year: '2021', url: 'https://arxiv.org/abs/2103.13413', category: 'blind-vision', type: 'model',
    usedIn: 'بديل دقيق لتقدير العمق',
    note: 'محوّلات الكثافة للتنبؤ بالعمق.' },
  { id: 'deepsort', title: 'Simple Online and Realtime Tracking with a Deep Association Metric', authors: 'Wojke, Bewley & Paulus', year: '2017', url: 'https://arxiv.org/abs/1703.07402', category: 'blind-vision', type: 'model',
    usedIn: 'تتبّع الأجسام بين الإطارات في عين الأعمى',
    note: 'تتبّع متعدد الأهداف مستقر للحركة.' },
  { id: 'sort-tracker', title: 'Simple Online and Realtime Tracking (SORT)', authors: 'Bewley et al.', year: '2016', url: 'https://arxiv.org/abs/1602.00763', category: 'blind-vision', type: 'model',
    usedIn: 'بديل خفيف للتتبّع',
    note: 'متتبّع بسيط مبني على فلتر كالمان.' },
  { id: 'tesseract', title: 'Tesseract OCR Engine', authors: 'Smith / Google', year: '2007', url: 'https://github.com/tesseract-ocr/tesseract', category: 'blind-vision', type: 'tool',
    usedIn: 'قراءة النصوص واللافتات في BlindEye (ocr.ts)',
    note: 'محرّك OCR مفتوح المصدر يدعم العربية.' },
  { id: 'tesseract-js', title: 'Tesseract.js — Pure JS OCR', authors: 'Naptha Project', year: '2024', url: 'https://github.com/naptha/tesseract.js', category: 'blind-vision', type: 'tool',
    usedIn: 'تنفيذ OCR داخل المتصفّح',
    note: 'تشغيل Tesseract محلياً عبر WebAssembly.' },
  { id: 'paddle-ocr', title: 'PaddleOCR Multilingual Engine', authors: 'PaddlePaddle Team', year: '2021', url: 'https://github.com/PaddlePaddle/PaddleOCR', category: 'blind-vision', type: 'tool',
    usedIn: 'احتياطي عربي عالي الدقة',
    note: 'محرّك OCR متعدد اللغات بدقة عالية.' },
  { id: 'face-api-js', title: 'face-api.js — Face Detection in the Browser', authors: 'Vincent Mühler', year: '2020', url: 'https://github.com/justadudewhohacks/face-api.js', category: 'blind-vision', type: 'tool',
    usedIn: 'التعرّف على وجوه الأقارب (مخطّط)',
    note: 'كشف وتعرّف على الوجوه عبر TensorFlow.js.' },
  { id: 'mtcnn-face', title: 'MTCNN — Joint Face Detection and Alignment', authors: 'Zhang et al.', year: '2016', url: 'https://arxiv.org/abs/1604.02878', category: 'blind-vision', type: 'model',
    usedIn: 'مكتشف الوجوه في face-api',
    note: 'كشف ومحاذاة الوجه متعدد المهام.' },
  { id: 'facenet', title: 'FaceNet — A Unified Embedding for Face Recognition', authors: 'Schroff, Kalenichenko & Philbin', year: '2015', url: 'https://arxiv.org/abs/1503.03832', category: 'blind-vision', type: 'model',
    usedIn: 'تشفير الوجوه للمقارنة',
    note: 'تضمينات الوجه المعتمدة في التعرّف.' },
  { id: 'onnx-runtime-web', title: 'ONNX Runtime Web', authors: 'Microsoft', year: '2023', url: 'https://onnxruntime.ai/docs/tutorials/web/', category: 'blind-vision', type: 'tool',
    usedIn: 'تشغيل YOLOv8/MiDaS محلياً في المتصفّح',
    note: 'تشغيل نماذج ML داخل المتصفّح بسرعة عالية.' },
  { id: 'mediapipe-hands', title: 'MediaPipe Hands', authors: 'Google Research', year: '2020', url: 'https://google.github.io/mediapipe/solutions/hands.html', category: 'sign-language', type: 'tool',
    usedIn: 'تتبّع مفاصل اليد في مترجم لغة الإشارة',
    note: 'كشف 21 مفصل لليد بدقة عالية.' },
  { id: 'mediapipe-pose', title: 'MediaPipe Pose / BlazePose', authors: 'Bazarevsky et al.', year: '2020', url: 'https://arxiv.org/abs/2006.10204', category: 'sign-language', type: 'model',
    usedIn: 'تتبّع الجسم في الإشارة',
    note: 'تتبّع 33 نقطة من الجسم في الزمن الفعلي.' },
  { id: 'web-speech-api', title: 'Web Speech API', authors: 'W3C', year: '2024', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API', category: 'speech-audio', type: 'standard',
    usedIn: 'الأوامر الصوتية والنطق في BlindEye',
    note: 'واجهة المتصفّح القياسية لتحويل الكلام/النص.' },
  { id: 'webrtc', title: 'WebRTC — Real-time Communications for the Web', authors: 'W3C / IETF', year: '2021', url: 'https://www.w3.org/TR/webrtc/', category: 'navigation-geo', type: 'standard',
    usedIn: 'تشغيل الكاميرا في عين الأعمى',
    note: 'معيار المتصفّح للوصول إلى الكاميرا والميكروفون.' },
  { id: 'device-orientation', title: 'DeviceOrientation Event Specification', authors: 'W3C', year: '2023', url: 'https://www.w3.org/TR/orientation-event/', category: 'navigation-geo', type: 'standard',
    usedIn: 'البوصلة في compass.ts',
    note: 'معيار قراءة الاتجاه من حساسات الجهاز.' },
  { id: 'device-motion', title: 'DeviceMotion Event Specification', authors: 'W3C', year: '2023', url: 'https://www.w3.org/TR/devicemotion/', category: 'navigation-geo', type: 'standard',
    usedIn: 'كشف السقوط في fallDetection.ts',
    note: 'قراءة بيانات التسارع لاكتشاف الحوادث.' },
  { id: 'porcupine', title: 'Porcupine Wake Word Engine', authors: 'Picovoice', year: '2023', url: 'https://picovoice.ai/platform/porcupine/', category: 'speech-audio', type: 'tool',
    usedIn: 'كلمة الاستيقاظ "يا عين"',
    note: 'محرّك كشف كلمة استيقاظ يعمل دون اتصال.' },
  { id: 'whisper-openai', title: 'Whisper — Robust Speech Recognition via Large-Scale Weak Supervision', authors: 'Radford et al. / OpenAI', year: '2022', url: 'https://arxiv.org/abs/2212.04356', category: 'speech-audio', type: 'model',
    usedIn: 'احتياطي تحويل الكلام إلى نص (عربي)',
    note: 'نموذج STT متعدد اللغات بدقة عالية للعربية.' },
  { id: 'elevenlabs-tts', title: 'ElevenLabs TTS — Multilingual Speech Synthesis', authors: 'ElevenLabs', year: '2024', url: 'https://elevenlabs.io/docs', category: 'speech-audio', type: 'tool',
    usedIn: 'صوت عربي طبيعي في BlindEye',
    note: 'محرّك TTS عالي الجودة بأصوات عربية.' },
  { id: 'openstreetmap', title: 'OpenStreetMap', authors: 'OSM Foundation', year: '2024', url: 'https://www.openstreetmap.org/about', category: 'navigation-geo', type: 'tool',
    usedIn: 'خرائط الأماكن في destinationParser.ts',
    note: 'خرائط حرّة للأماكن والشوارع.' },
  { id: 'nominatim', title: 'Nominatim — OSM Geocoding', authors: 'OSM Foundation', year: '2024', url: 'https://nominatim.org/', category: 'navigation-geo', type: 'tool',
    usedIn: 'تحويل أسماء الأماكن إلى إحداثيات',
    note: 'خدمة geocoding مجانية مبنية على OSM.' },
  { id: 'mapbox-directions', title: 'Mapbox Directions API', authors: 'Mapbox', year: '2024', url: 'https://docs.mapbox.com/api/navigation/directions/', category: 'navigation-geo', type: 'tool',
    usedIn: 'الملاحة خطوة بخطوة (مخطّط)',
    note: 'حساب مسارات المشي والقيادة.' },
  { id: 'haversine', title: 'Haversine formula', authors: 'Sinnott', year: '1984', url: 'https://en.wikipedia.org/wiki/Haversine_formula', category: 'navigation-geo', type: 'research',
    usedIn: 'حساب المسافات في geo.ts',
    note: 'صيغة لحساب المسافة بين نقطتين على الكرة الأرضية.' },
  { id: 'who-blindness', title: 'WHO World Report on Vision', authors: 'WHO', year: '2019', url: 'https://www.who.int/publications/i/item/9789241516570', category: 'blind-vision', type: 'guideline',
    usedIn: 'إحصاءات صفحة عين الأعمى',
    note: 'تقرير عالمي شامل عن صحة البصر.' },

  // ============================================================
  // 6) BRAILLE (15)
  // ============================================================
  { id: 'iso-tr-11548', title: 'ISO/TR 11548 — Braille Communications', authors: 'ISO', year: '2001', url: 'https://www.iso.org/standard/35439.html', category: 'braille', type: 'standard',
    usedIn: 'ترميز بريل في features/braille',
    note: 'المعيار الدولي لتبادل بريل.' },
  { id: 'unicode-braille', title: 'Unicode Braille Patterns (U+2800–U+28FF)', authors: 'Unicode Consortium', year: '1999', url: 'https://www.unicode.org/charts/PDF/U2800.pdf', category: 'braille', type: 'standard',
    usedIn: 'unicodeBraille.ts لتوليد الأنماط',
    note: 'الكتلة الرسمية لرموز بريل في يونيكود.' },
  { id: 'liblouis', title: 'Liblouis — Open-source Braille Translator', authors: 'Liblouis Team', year: '2024', url: 'https://liblouis.io/', category: 'braille', type: 'tool',
    usedIn: 'مرجع تحويل النصوص إلى بريل',
    note: 'مكتبة قياسية لترجمة بريل في 100+ لغة.' },
  { id: 'arabic-braille', title: 'World Braille Usage — Arabic', authors: 'UNESCO', year: '2013', url: 'https://www.perkins.org/wp-content/uploads/2022/06/WorldBrailleUsage3.pdf', category: 'braille', type: 'standard',
    usedIn: 'جدول الحروف العربية في brailleAlphabet.ts',
    note: 'المعيار العالمي لاستخدام بريل في 142 لغة.' },
  { id: 'nemeth-code', title: 'Nemeth Braille Code for Mathematics', authors: 'Abraham Nemeth', year: '1972', url: 'https://www.brailleauthority.org/mathscience/nemeth1972.pdf', category: 'braille', type: 'standard',
    usedIn: 'بريل الرياضيات في الدروس',
    note: 'الترميز الرسمي للرياضيات في بريل.' },
  { id: 'ueb', title: 'Unified English Braille (UEB)', authors: 'ICEB', year: '2013', url: 'https://www.iceb.org/ueb.html', category: 'braille', type: 'standard',
    usedIn: 'مرجع البريل الإنجليزي الموحّد',
    note: 'البريل الإنجليزي الموحّد بين الدول.' },
  { id: 'braille-music', title: 'Braille Music Code', authors: 'BANA', year: '2015', url: 'https://www.brailleauthority.org/music/music.pdf', category: 'braille', type: 'standard',
    usedIn: 'مخطّط بريل الموسيقى',
    note: 'ترميز الموسيقى في بريل.' },
  { id: 'tactile-graphics', title: 'Guidelines and Standards for Tactile Graphics', authors: 'BANA', year: '2010', url: 'https://www.brailleauthority.org/tg/', category: 'braille', type: 'guideline',
    usedIn: 'tactilePdf.ts و tactileSvg.ts',
    note: 'معايير الرسوم اللمسية للمكفوفين.' },
  { id: 'braille-display-usb-hid', title: 'USB HID Braille Display Specification', authors: 'USB-IF', year: '2018', url: 'https://www.usb.org/sites/default/files/hutrr74_-_braille_display.pdf', category: 'braille', type: 'standard',
    usedIn: 'دعم شاشات البريل (مخطّط)',
    note: 'بروتوكول USB-HID لشاشات بريل.' },
  { id: 'wcag-2-2', title: 'WCAG 2.2 — Web Content Accessibility Guidelines', authors: 'W3C', year: '2023', url: 'https://www.w3.org/TR/WCAG22/', category: 'inclusive-edu', type: 'standard',
    usedIn: 'معايير الوصول في كل المنصة',
    note: 'إرشادات إتاحة محتوى الويب.' },
  { id: 'aria', title: 'WAI-ARIA 1.2', authors: 'W3C', year: '2023', url: 'https://www.w3.org/TR/wai-aria-1.2/', category: 'inclusive-edu', type: 'standard',
    usedIn: 'سمات إمكانية الوصول في المكوّنات',
    note: 'معيار وصف عناصر الواجهات للقارئات الشاشية.' },
  { id: 'nvda', title: 'NVDA Screen Reader', authors: 'NV Access', year: '2024', url: 'https://www.nvaccess.org/', category: 'inclusive-edu', type: 'tool',
    usedIn: 'اختبار قارئ الشاشة المجاني',
    note: 'قارئ شاشة مفتوح المصدر لـ Windows.' },
  { id: 'jaws', title: 'JAWS Screen Reader', authors: 'Freedom Scientific', year: '2024', url: 'https://www.freedomscientific.com/products/software/jaws/', category: 'inclusive-edu', type: 'tool',
    usedIn: 'اختبار التوافق مع قارئ JAWS',
    note: 'قارئ الشاشة التجاري الأشهر.' },
  { id: 'voiceover', title: 'Apple VoiceOver', authors: 'Apple', year: '2024', url: 'https://www.apple.com/accessibility/vision/', category: 'inclusive-edu', type: 'tool',
    usedIn: 'اختبار التوافق على iOS/macOS',
    note: 'قارئ الشاشة المدمج في أجهزة Apple.' },
  { id: 'braille-learning', title: 'Foundations of Braille Literacy', authors: 'Wormsley & D\'Andrea', year: '1997', url: 'https://www.aph.org/braille-literacy/', category: 'braille', type: 'book',
    usedIn: 'بناء دروس BrailleHome',
    note: 'منهجية تعليم بريل للأطفال والكبار.' },

  // ============================================================
  // 7) SIGN LANGUAGE / DEAF (20)
  // ============================================================
  { id: 'wfd', title: 'World Federation of the Deaf — Position Papers', authors: 'WFD', year: '2024', url: 'https://wfdeaf.org/', category: 'sign-language', type: 'guideline',
    usedIn: 'مرجعية لغات الإشارة في features/sign-language',
    note: 'الاتحاد العالمي للصم — معايير لغات الإشارة.' },
  { id: 'arabic-sign-arsl', title: 'Unified Arabic Sign Language Dictionary', authors: 'League of Arab States / ArSL Council', year: '2014', url: 'https://www.lasportal.org/', category: 'sign-language', type: 'standard',
    usedIn: 'قاموس الإشارة العربية الموحّد في dictionary/',
    note: 'القاموس العربي الموحّد للغة الإشارة.' },
  { id: 'asl-stokoe', title: 'Sign Language Structure', authors: 'William Stokoe', year: '1960', url: 'https://gupress.gallaudet.edu/excerpts/SLSch1.html', category: 'sign-language', type: 'book',
    usedIn: 'تصنيف Handshapes',
    note: 'العمل المؤسس لاعتبار لغة الإشارة لغة كاملة.' },
  { id: 'hamnosys', title: 'HamNoSys — Hamburg Notation System', authors: 'University of Hamburg', year: '1989', url: 'https://www.sign-lang.uni-hamburg.de/hamnosys.html', category: 'sign-language', type: 'standard',
    usedIn: 'تمثيل الإشارات في signSystems.ts',
    note: 'نظام تدوين عالمي لإشارات لغات الصم.' },
  { id: 'sign-writing', title: 'SignWriting', authors: 'Valerie Sutton', year: '1974', url: 'https://www.signwriting.org/', category: 'sign-language', type: 'standard',
    usedIn: 'مرجع تمثيل إضافي للإشارات',
    note: 'نظام كتابي بصري للإشارات.' },
  { id: 'how2sign', title: 'How2Sign — Multimodal ASL Dataset', authors: 'Duarte et al.', year: '2021', url: 'https://how2sign.github.io/', category: 'sign-language', type: 'dataset',
    usedIn: 'مرجع بناء قاموس الإشارة',
    note: 'مجموعة بيانات كبيرة للإشارة الأمريكية.' },
  { id: 'wlasl', title: 'WLASL — Word-Level American Sign Language', authors: 'Li et al.', year: '2020', url: 'https://dxli94.github.io/WLASL/', category: 'sign-language', type: 'dataset',
    usedIn: 'تدريب النماذج (مرجع)',
    note: 'أكبر مجموعة بيانات للإشارات على مستوى الكلمات.' },
  { id: 'i3d-sign', title: 'Sign Language Recognition with 3D ConvNets', authors: 'Joze & Koller', year: '2019', url: 'https://arxiv.org/abs/1812.01053', category: 'sign-language', type: 'research',
    usedIn: 'مرجع نماذج تمييز الإشارة',
    note: 'استخدام شبكات الالتفاف ثلاثية الأبعاد في الإشارة.' },
  { id: 'mediapipe-holistic', title: 'MediaPipe Holistic', authors: 'Google Research', year: '2020', url: 'https://google.github.io/mediapipe/solutions/holistic.html', category: 'sign-language', type: 'tool',
    usedIn: 'تتبّع اليد والوجه والجسم معاً',
    note: 'حل شامل لتتبّع الجسم كاملاً.' },
  { id: 'kalman-filter', title: 'A New Approach to Linear Filtering and Prediction', authors: 'Kalman', year: '1960', url: 'https://www.cs.unc.edu/~welch/kalman/media/pdf/Kalman1960.pdf', category: 'sign-language', type: 'research',
    usedIn: 'تثبيت إشارة المفاصل في gestureFilter.ts',
    note: 'فلتر كالمان لتنعيم بيانات المستشعرات.' },
  { id: 'dtw-sign', title: 'Dynamic Time Warping for Sign Recognition', authors: 'Lichtenauer et al.', year: '2008', url: 'https://ieeexplore.ieee.org/document/4543271', category: 'sign-language', type: 'research',
    usedIn: 'مطابقة تسلسل الإشارات',
    note: 'مطابقة تسلسلات متفاوتة الزمن.' },
  { id: 'bsl-corpus', title: 'British Sign Language Corpus', authors: 'Schembri et al.', year: '2014', url: 'https://bslcorpusproject.org/', category: 'sign-language', type: 'dataset',
    usedIn: 'مرجع لغوي للإشارة البريطانية',
    note: 'مدوّنة مرجعية للغة الإشارة البريطانية.' },
  { id: 'deaf-culture-ladd', title: 'Understanding Deaf Culture: In Search of Deafhood', authors: 'Paddy Ladd', year: '2003', url: 'https://www.multilingual-matters.com/page/detail/?k=9781853595455', category: 'sign-language', type: 'book',
    usedIn: 'محتوى تثقيفي في SignHome',
    note: 'مرجع أساسي لثقافة الصم.' },
  { id: 'who-hearing', title: 'WHO World Report on Hearing', authors: 'WHO', year: '2021', url: 'https://www.who.int/publications/i/item/9789240020481', category: 'sign-language', type: 'guideline',
    usedIn: 'إحصاءات قسم الصم',
    note: 'تقرير منظمة الصحة عن السمع عالمياً.' },
  { id: 'crpd-art21', title: 'UN CRPD Article 21 — Freedom of Expression and Access to Information', authors: 'United Nations', year: '2006', url: 'https://www.un.org/development/desa/disabilities/convention-on-the-rights-of-persons-with-disabilities/article-21-freedom-of-expression-and-opinion-and-access-to-information.html', category: 'sign-language', type: 'guideline',
    usedIn: 'الأساس الحقوقي للإتاحة',
    note: 'حق الصم في الاعتراف بلغات الإشارة.' },
  { id: 'sign-translator-zhou', title: 'Sign Language Transformers', authors: 'Camgöz et al.', year: '2020', url: 'https://arxiv.org/abs/2003.13830', category: 'sign-language', type: 'research',
    usedIn: 'مرجع ترجمة الإشارة العصبية',
    note: 'محوّلات لترجمة الإشارة إلى نص.' },
  { id: 'openpose', title: 'OpenPose — Realtime Multi-Person Keypoint Detection', authors: 'Cao et al.', year: '2019', url: 'https://arxiv.org/abs/1812.08008', category: 'sign-language', type: 'model',
    usedIn: 'بديل لتتبّع الجسم في الإشارة',
    note: 'نظام تتبّع نقاط الجسم متعدد الأشخاص.' },
  { id: 'cued-speech', title: 'Cued Speech', authors: 'Cornett', year: '1967', url: 'https://cuedspeech.org/', category: 'sign-language', type: 'standard',
    usedIn: 'وضع تكميلي للنطق المرئي',
    note: 'نظام إشارات يدوية لتوضيح النطق.' },
  { id: 'lipnet', title: 'LipNet — End-to-End Sentence-level Lipreading', authors: 'Assael et al.', year: '2016', url: 'https://arxiv.org/abs/1611.01599', category: 'sign-language', type: 'research',
    usedIn: 'مرجع قراءة الشفاه (مخطّط)',
    note: 'قراءة الشفاه بشبكات عصبية.' },
  { id: 'fingerspelling', title: 'American Sign Language Fingerspelling Recognition', authors: 'Shi et al.', year: '2018', url: 'https://arxiv.org/abs/1810.11438', category: 'sign-language', type: 'research',
    usedIn: 'تمييز التهجئة بالأصابع',
    note: 'تمييز التهجئة الإشارية بأصابع اليد.' },

  // ============================================================
  // 8) SENSORY (15)
  // ============================================================
  { id: 'sensory-profile-2', title: 'Sensory Profile 2', authors: 'Dunn', year: '2014', url: 'https://www.pearsonassessments.com/store/usassessments/en/Store/Professional-Assessments/Behavior/Sensory-Profile-2/p/100000822.html', category: 'sensory', type: 'tool',
    usedIn: 'SensoryProfileSetup',
    note: 'الإصدار الثاني من ملف Dunn الحسي.' },
  { id: 'mippa', title: 'Miller Function & Participation Scales', authors: 'Miller', year: '2006', url: 'https://www.pearsonassessments.com/store/usassessments/en/Store/Professional-Assessments/Motor-Sensory/Miller-Function-%26-Participation-Scales/p/100000463.html', category: 'sensory', type: 'tool',
    usedIn: 'تقييم المشاركة الحسية',
    note: 'مقياس وظيفة الطفل ومشاركته.' },
  { id: 'spd-foundation', title: 'Sensory Processing Disorder Foundation', authors: 'STAR Institute', year: '2024', url: 'https://www.spdstar.org/', category: 'sensory', type: 'guideline',
    usedIn: 'مرجعية اضطراب المعالجة الحسية',
    note: 'مرجع علمي معاصر لاضطراب المعالجة الحسية.' },
  { id: 'ayres-frame', title: 'Ayres Sensory Integration', authors: 'Roley et al.', year: '2007', url: 'https://www.aota.org/practice/clinical-topics/sensory-integration', category: 'sensory', type: 'guideline',
    usedIn: 'إطار التدخّل الحسي',
    note: 'إطار آيرز للتكامل الحسي السريري.' },
  { id: 'sensation-and-perception-goldstein', title: 'Sensation and Perception', authors: 'Goldstein', year: '2016', url: 'https://www.cengage.com/c/sensation-and-perception-10e-goldstein', category: 'sensory', type: 'book',
    usedIn: 'أساس علمي لمحاكاة الحواس',
    note: 'كتاب علم النفس الحسي المرجعي.' },
  { id: 'visual-snow', title: 'Visual Snow Syndrome', authors: 'Schankin et al.', year: '2014', url: 'https://academic.oup.com/brain/article/137/5/1419/355716', category: 'sensory', type: 'research',
    usedIn: 'محاكاة الاضطرابات البصرية',
    note: 'متلازمة الثلج البصري.' },
  { id: 'photophobia', title: 'Photophobia: Mechanisms and Management', authors: 'Digre & Brennan', year: '2012', url: 'https://pubmed.ncbi.nlm.nih.gov/22381574/', category: 'sensory', type: 'research',
    usedIn: 'وضع تخفيف الإضاءة',
    note: 'الحساسية للضوء وإدارتها.' },
  { id: 'auditory-hypersens', title: 'Auditory Hypersensitivity in ASD', authors: 'Stiegler & Davis', year: '2010', url: 'https://pubmed.ncbi.nlm.nih.gov/19858547/', category: 'sensory', type: 'research',
    usedIn: 'وضع تقليل الضوضاء',
    note: 'فرط الحساسية السمعية لدى التوحّد.' },
  { id: 'proprioception-blanche', title: 'Proprioception: A Hidden Sense', authors: 'Blanche & Schaaf', year: '2001', url: 'https://pubmed.ncbi.nlm.nih.gov/11722089/', category: 'sensory', type: 'research',
    usedIn: 'تمارين الإحساس بالموضع',
    note: 'الحس العميق ودوره في التنظيم.' },
  { id: 'vestibular', title: 'Vestibular Processing Dysfunction in Children', authors: 'Cohn et al.', year: '2017', url: 'https://pubmed.ncbi.nlm.nih.gov/28840837/', category: 'sensory', type: 'research',
    usedIn: 'وضع الاتزان',
    note: 'اضطراب المعالجة الدهليزية.' },
  { id: 'haptic-feedback', title: 'Vibration Haptic Feedback Standards', authors: 'IEEE TVCG', year: '2019', url: 'https://ieeexplore.ieee.org/document/8624453', category: 'sensory', type: 'research',
    usedIn: 'hapticBus.ts للاهتزاز',
    note: 'معايير ردود الفعل الاهتزازية.' },
  { id: 'navigator-vibrate', title: 'Vibration API (W3C)', authors: 'W3C', year: '2016', url: 'https://www.w3.org/TR/vibration/', category: 'sensory', type: 'standard',
    usedIn: 'navigator.vibrate في hapticBus',
    note: 'معيار المتصفّح لتشغيل الاهتزاز.' },
  { id: 'sensory-room', title: 'Multi-Sensory Environment (Snoezelen)', authors: 'Hulsegge & Verheul', year: '1987', url: 'https://www.snoezeleninfo.com/', category: 'sensory', type: 'book',
    usedIn: 'تصميم SensoryOutput',
    note: 'الغرف الحسية المتعددة المنشأ في هولندا.' },
  { id: 'self-regulation', title: 'The Alert Program: How Does Your Engine Run?', authors: 'Williams & Shellenberger', year: '1996', url: 'https://www.alertprogram.com/', category: 'sensory', type: 'tool',
    usedIn: 'منظّم الحالة الحسية',
    note: 'برنامج تنظيم الذات الحسي.' },
  { id: 'zones-regulation', title: 'The Zones of Regulation', authors: 'Leah Kuypers', year: '2011', url: 'https://www.zonesofregulation.com/', category: 'sensory', type: 'book',
    usedIn: 'مناطق التنظيم العاطفي',
    note: 'إطار شائع لتعليم التنظيم العاطفي.' },

  // ============================================================
  // 9) CLINICAL AI (15)
  // ============================================================
  { id: 'merck-manual', title: 'The Merck Manual of Diagnosis and Therapy', authors: 'Merck', year: '2023', url: 'https://www.merckmanuals.com/', category: 'clinical-ai', type: 'book',
    usedIn: 'محتوى الحالات السريرية في ClinicalCases',
    note: 'المرجع الطبي الأكثر شيوعاً عالمياً.' },
  { id: 'harrison-internal', title: 'Harrison\'s Principles of Internal Medicine', authors: 'Jameson et al.', year: '2022', url: 'https://accessmedicine.mhmedical.com/book.aspx?bookid=3095', category: 'clinical-ai', type: 'book',
    usedIn: 'حالات الطب الباطني',
    note: 'مرجع الطب الباطني الأشهر.' },
  { id: 'uptodate', title: 'UpToDate Clinical Reference', authors: 'Wolters Kluwer', year: '2024', url: 'https://www.uptodate.com/', category: 'clinical-ai', type: 'tool',
    usedIn: 'مراجعة بروتوكولات التشخيص',
    note: 'قاعدة معرفة سريرية محدّثة.' },
  { id: 'who-icd11', title: 'WHO ICD-11', authors: 'WHO', year: '2022', url: 'https://icd.who.int/', category: 'clinical-ai', type: 'standard',
    usedIn: 'ترميز التشخيصات في تقارير ClinicalReport',
    note: 'التصنيف الدولي للأمراض الإصدار 11.' },
  { id: 'aha-cpr-2020', title: 'AHA Guidelines for CPR and ECC', authors: 'American Heart Association', year: '2020', url: 'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines', category: 'clinical-ai', type: 'guideline',
    usedIn: 'محاكاة AED في InteractiveAED',
    note: 'إرشادات الإنعاش القلبي الرئوي العالمية.' },
  { id: 'ecg-mason', title: 'Mason-Likar 12-Lead ECG System', authors: 'Mason & Likar', year: '1966', url: 'https://pubmed.ncbi.nlm.nih.gov/5916709/', category: 'clinical-ai', type: 'research',
    usedIn: 'محاكاة InteractiveECG',
    note: 'نظام تخطيط القلب الـ 12 الاسلاكي.' },
  { id: 'stethoscope-bohadana', title: 'Fundamentals of Lung Auscultation', authors: 'Bohadana et al.', year: '2014', url: 'https://www.nejm.org/doi/full/10.1056/NEJMra1302901', category: 'clinical-ai', type: 'research',
    usedIn: 'محاكاة InteractiveStethoscope',
    note: 'أساسيات سماعة الصدر السريرية.' },
  { id: 'apgar', title: 'Apgar Score', authors: 'Virginia Apgar', year: '1953', url: 'https://pubmed.ncbi.nlm.nih.gov/13083014/', category: 'clinical-ai', type: 'research',
    usedIn: 'بنود تقييم المواليد',
    note: 'مقياس أبجار لتقييم حديثي الولادة.' },
  { id: 'gcs', title: 'Glasgow Coma Scale', authors: 'Teasdale & Jennett', year: '1974', url: 'https://www.glasgowcomascale.org/', category: 'clinical-ai', type: 'tool',
    usedIn: 'بنود تقييم الوعي',
    note: 'مقياس غلاسكو للغيبوبة.' },
  { id: 'news2', title: 'NEWS2 — National Early Warning Score 2', authors: 'RCP UK', year: '2017', url: 'https://www.rcp.ac.uk/improving-care/resources/national-early-warning-score-news-2/', category: 'clinical-ai', type: 'tool',
    usedIn: 'VitalsMonitor.tsx',
    note: 'مقياس الإنذار المبكر للعلامات الحيوية.' },
  { id: 'sepsis-3', title: 'Sepsis-3 Definitions', authors: 'Singer et al.', year: '2016', url: 'https://jamanetwork.com/journals/jama/fullarticle/2492881', category: 'clinical-ai', type: 'guideline',
    usedIn: 'كشف الإنذار في الحالات',
    note: 'التعريف الحديث للإنتان السريري.' },
  { id: 'ai-radiology-rajpurkar', title: 'AI in Radiology — CheXNet', authors: 'Rajpurkar et al.', year: '2017', url: 'https://arxiv.org/abs/1711.05225', category: 'clinical-ai', type: 'research',
    usedIn: 'مرجع AI الطبي',
    note: 'كشف الالتهاب الرئوي بالأشعة بالتعلم العميق.' },
  { id: 'who-first-aid', title: 'WHO First Aid Guidelines', authors: 'WHO', year: '2020', url: 'https://www.who.int/publications/i/item/9789241549615', category: 'clinical-ai', type: 'guideline',
    usedIn: 'محتوى المساعد الطبي المدرسي',
    note: 'دليل الإسعافات الأولية العالمي.' },
  { id: 'pediatric-ils', title: 'European Resuscitation Council Guidelines (Paediatric)', authors: 'ERC', year: '2021', url: 'https://www.erc.edu/', category: 'clinical-ai', type: 'guideline',
    usedIn: 'بروتوكولات الإنعاش للأطفال',
    note: 'إرشادات الإنعاش الأوروبية.' },
  { id: 'patient-safety-iom', title: 'To Err is Human — Patient Safety', authors: 'Institute of Medicine', year: '2000', url: 'https://nap.nationalacademies.org/catalog/9728', category: 'clinical-ai', type: 'book',
    usedIn: 'بروتوكولات الأمان السريري',
    note: 'الكتاب المؤسس لسلامة المرضى.' },

  // ============================================================
  // 10) INCLUSIVE EDUCATION (15)
  // ============================================================
  { id: 'unesco-inclusive', title: 'UNESCO Guidelines for Inclusion: Ensuring Access to Education for All', authors: 'UNESCO', year: '2005', url: 'https://unesdoc.unesco.org/ark:/48223/pf0000140224', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'إطار المنصة الدامجة كاملاً',
    note: 'المرجع المؤسس للتعليم الدامج عالمياً.' },
  { id: 'unesco-salamanca', title: 'Salamanca Statement on Special Needs Education', authors: 'UNESCO', year: '1994', url: 'https://unesdoc.unesco.org/ark:/48223/pf0000098427', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'الفلسفة المؤسسة للدمج',
    note: 'البيان التاريخي لحق الجميع في التعليم.' },
  { id: 'crpd-art24', title: 'UN CRPD Article 24 — Education', authors: 'United Nations', year: '2006', url: 'https://www.un.org/development/desa/disabilities/convention-on-the-rights-of-persons-with-disabilities/article-24-education.html', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'الأساس الحقوقي للمنصة',
    note: 'حق ذوي الإعاقة في التعليم الدامج.' },
  { id: 'icf-cy', title: 'WHO ICF-CY — Children and Youth Version', authors: 'WHO', year: '2007', url: 'https://www.who.int/standards/classifications/international-classification-of-functioning-disability-and-health/icf-versions/icf-cy', category: 'inclusive-edu', type: 'standard',
    usedIn: 'تصنيف القدرات الوظيفية',
    note: 'التصنيف الدولي لوظائف الأطفال.' },
  { id: 'udl', title: 'Universal Design for Learning Guidelines 3.0', authors: 'CAST', year: '2024', url: 'https://udlguidelines.cast.org/', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'إطار التصميم الشامل في المنصة',
    note: 'إرشادات التصميم الشامل للتعلّم.' },
  { id: 'idea-act', title: 'Individuals with Disabilities Education Act (IDEA)', authors: 'US Congress', year: '2004', url: 'https://sites.ed.gov/idea/', category: 'inclusive-edu', type: 'standard',
    usedIn: 'مرجع الـ IEP',
    note: 'القانون الأمريكي للتعليم الخاص.' },
  { id: 'rti', title: 'Response to Intervention Framework', authors: 'NCRTI', year: '2010', url: 'https://www.rti4success.org/', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'مسار التدخّل التدرّجي',
    note: 'نموذج الاستجابة للتدخّل في المدارس.' },
  { id: 'pbis', title: 'Positive Behavior Interventions & Supports', authors: 'OSEP Center', year: '2024', url: 'https://www.pbis.org/', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'نظام السلوك الإيجابي',
    note: 'دعم السلوك الإيجابي على مستوى المدرسة.' },
  { id: 'pisa-inclusion', title: 'PISA Equity in Education Report', authors: 'OECD', year: '2018', url: 'https://www.oecd.org/pisa/publications/PISA2018_CN_IDN.pdf', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'مؤشرات قياس الأثر',
    note: 'تقرير OECD حول العدالة التعليمية.' },
  { id: 'gem-inclusion', title: 'Global Education Monitoring Report — Inclusion', authors: 'UNESCO GEM', year: '2020', url: 'https://unesdoc.unesco.org/ark:/48223/pf0000373718', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'إحصاءات الدمج',
    note: 'تقرير اليونسكو السنوي عن التعليم الدامج.' },
  { id: 'sdg4', title: 'UN SDG 4 — Quality Education', authors: 'United Nations', year: '2015', url: 'https://sdgs.un.org/goals/goal4', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'مواءمة المنصة مع SDG4',
    note: 'الهدف الرابع للتنمية المستدامة.' },
  { id: 'arabic-disability-law', title: 'القانون الأردني لحقوق الأشخاص ذوي الإعاقة (20/2017)', authors: 'الأردن', year: '2017', url: 'https://hcd.gov.jo/', category: 'inclusive-edu', type: 'standard',
    usedIn: 'الإطار القانوني المحلي',
    note: 'القانون الأردني لحماية حقوق ذوي الإعاقة.' },
  { id: 'whod-disability', title: 'World Report on Disability', authors: 'WHO & World Bank', year: '2011', url: 'https://www.who.int/publications/i/item/9789241564182', category: 'inclusive-edu', type: 'guideline',
    usedIn: 'إحصاءات الإعاقة العالمية',
    note: 'أول تقرير عالمي شامل عن الإعاقة.' },
  { id: 'inclusion-stainback', title: 'Inclusion: A Guide for Educators', authors: 'Stainback & Stainback', year: '1996', url: 'https://www.brookespublishing.com/product/inclusion-a-guide-for-educators/', category: 'inclusive-edu', type: 'book',
    usedIn: 'محتوى تدريب المعلمين',
    note: 'كتاب أساسي للمعلمين في التعليم الدامج.' },
  { id: 'tomlinson-differentiation', title: 'The Differentiated Classroom', authors: 'Carol Ann Tomlinson', year: '2014', url: 'https://www.ascd.org/books/the-differentiated-classroom-2nd-edition', category: 'inclusive-edu', type: 'book',
    usedIn: 'إطار التعليم المتمايز',
    note: 'مرجع التعليم المتمايز عالمياً.' },

  // ============================================================
  // 11) SPEECH / AUDIO (10)
  // ============================================================
  { id: 'tacotron2', title: 'Tacotron 2 — Natural TTS Synthesis', authors: 'Shen et al. / Google', year: '2018', url: 'https://arxiv.org/abs/1712.05884', category: 'speech-audio', type: 'model',
    usedIn: 'بنية TTS الاحتياطية',
    note: 'نموذج توليد كلام طبيعي بشبكات Seq2Seq.' },
  { id: 'wavenet', title: 'WaveNet: A Generative Model for Raw Audio', authors: 'van den Oord et al.', year: '2016', url: 'https://arxiv.org/abs/1609.03499', category: 'speech-audio', type: 'model',
    usedIn: 'مرجع جودة الصوت في TTS',
    note: 'نموذج DeepMind لتوليد الموجات الصوتية.' },
  { id: 'deep-speech', title: 'Deep Speech 2', authors: 'Amodei et al. / Baidu', year: '2016', url: 'https://arxiv.org/abs/1512.02595', category: 'speech-audio', type: 'model',
    usedIn: 'بديل STT عربي محلي',
    note: 'نظام تحويل كلام إلى نص بشبكات RNN.' },
  { id: 'vosk', title: 'Vosk Offline Speech Recognition', authors: 'Alpha Cephei', year: '2024', url: 'https://alphacephei.com/vosk/', category: 'speech-audio', type: 'tool',
    usedIn: 'STT دون اتصال (مخطّط)',
    note: 'محرّك تعرّف كلام بدون إنترنت يدعم العربية.' },
  { id: 'webaudio-api', title: 'Web Audio API', authors: 'W3C', year: '2021', url: 'https://www.w3.org/TR/webaudio/', category: 'speech-audio', type: 'standard',
    usedIn: 'تشغيل الأصوات والتنبيهات',
    note: 'معيار المتصفّح لمعالجة الصوت.' },
  { id: 'speech-synthesis-arabic', title: 'Arabic Speech Synthesis: Survey', authors: 'Halabi & Wald', year: '2016', url: 'https://www.sciencedirect.com/science/article/pii/S2210832716300047', category: 'speech-audio', type: 'research',
    usedIn: 'تقييم محرّكات TTS العربية',
    note: 'مراجعة شاملة لتوليد الكلام العربي.' },
  { id: 'arabic-asr', title: 'Arabic ASR with Conformer', authors: 'Hussein et al.', year: '2022', url: 'https://arxiv.org/abs/2204.07171', category: 'speech-audio', type: 'research',
    usedIn: 'تحسين دقة STT العربية',
    note: 'نموذج conformer للكلام العربي.' },
  { id: 'mfcc', title: 'Mel-Frequency Cepstral Coefficients', authors: 'Davis & Mermelstein', year: '1980', url: 'https://ieeexplore.ieee.org/document/1163420', category: 'speech-audio', type: 'research',
    usedIn: 'تحليل الصوت في المساعد الطبي',
    note: 'تمثيل المعاملات الميل-تكرارية للصوت.' },
  { id: 'noise-suppression-rnnoise', title: 'RNNoise: Real-Time Noise Suppression', authors: 'Valin', year: '2018', url: 'https://jmvalin.ca/demo/rnnoise/', category: 'speech-audio', type: 'model',
    usedIn: 'تقليل الضوضاء في الميكروفون',
    note: 'إزالة ضوضاء بزمن حقيقي عبر RNN.' },
  { id: 'webrtc-aec', title: 'WebRTC Acoustic Echo Cancellation', authors: 'Google', year: '2020', url: 'https://webrtc.googlesource.com/src/+/refs/heads/main/modules/audio_processing/', category: 'speech-audio', type: 'tool',
    usedIn: 'معالجة الصدى في الميكروفون',
    note: 'مكتبة إزالة الصدى الصوتي في WebRTC.' },

  // ============================================================
  // 12) NAVIGATION / GEO (10)
  // ============================================================
  { id: 'gps-elliott', title: 'Understanding GPS Principles and Applications', authors: 'Kaplan & Hegarty', year: '2017', url: 'https://us.artechhouse.com/Understanding-GPS-GNSS-Principles-and-Applications-Third-Edition-P1965.aspx', category: 'navigation-geo', type: 'book',
    usedIn: 'أساسيات geo.ts',
    note: 'الكتاب المرجعي لمبادئ GPS.' },
  { id: 'a-star', title: 'A* Search Algorithm', authors: 'Hart, Nilsson & Raphael', year: '1968', url: 'https://ieeexplore.ieee.org/document/4082128', category: 'navigation-geo', type: 'research',
    usedIn: 'حساب مسارات الملاحة',
    note: 'خوارزمية البحث الأمثل المعتمدة.' },
  { id: 'dijkstra', title: 'A Note on Two Problems in Connexion with Graphs', authors: 'Dijkstra', year: '1959', url: 'https://www-m3.ma.tum.de/foswiki/pub/MN0506/WebHome/dijkstra.pdf', category: 'navigation-geo', type: 'research',
    usedIn: 'مسار بديل للملاحة',
    note: 'خوارزمية ديكسترا لأقصر مسار.' },
  { id: 'osrm', title: 'OSRM — Open Source Routing Machine', authors: 'Project OSRM', year: '2024', url: 'http://project-osrm.org/', category: 'navigation-geo', type: 'tool',
    usedIn: 'محرّك توجيه مفتوح المصدر',
    note: 'خدمة توجيه سريعة مبنية على OSM.' },
  { id: 'geolocation-api', title: 'Geolocation API', authors: 'W3C', year: '2022', url: 'https://www.w3.org/TR/geolocation/', category: 'navigation-geo', type: 'standard',
    usedIn: 'تحديد موقع المستخدم في عين الأعمى',
    note: 'معيار المتصفّح لتحديد الموقع.' },
  { id: 'turf-js', title: 'Turf.js — Geospatial Analysis', authors: 'Mapbox', year: '2024', url: 'https://turfjs.org/', category: 'navigation-geo', type: 'tool',
    usedIn: 'حسابات جغرافية مساعدة',
    note: 'مكتبة JS للعمليات الجغرافية.' },
  { id: 'leaflet', title: 'Leaflet — JavaScript Mapping Library', authors: 'Vladimir Agafonkin', year: '2024', url: 'https://leafletjs.com/', category: 'navigation-geo', type: 'tool',
    usedIn: 'عرض الخرائط في الملاحة',
    note: 'مكتبة خرائط مفتوحة المصدر.' },
  { id: 'mapbox-gl', title: 'Mapbox GL JS', authors: 'Mapbox', year: '2024', url: 'https://docs.mapbox.com/mapbox-gl-js/', category: 'navigation-geo', type: 'tool',
    usedIn: 'الخرائط ثلاثية الأبعاد (مخطّط)',
    note: 'محرّك خرائط ويب متقدّم.' },
  { id: 'indoor-ble', title: 'Bluetooth LE Indoor Positioning', authors: 'Faragher & Harle', year: '2015', url: 'https://ieeexplore.ieee.org/document/7103024', category: 'navigation-geo', type: 'research',
    usedIn: 'مرجع الملاحة الداخلية',
    note: 'الملاحة الداخلية بإشارات البلوتوث.' },
  { id: 'arcore-arkit', title: 'ARCore / ARKit Specifications', authors: 'Google / Apple', year: '2024', url: 'https://developers.google.com/ar', category: 'navigation-geo', type: 'tool',
    usedIn: 'الواقع المعزّز للملاحة (مخطّط)',
    note: 'منصات الواقع المعزّز للأجهزة المحمولة.' },

  // ============================================================
  // 13) AI FOUNDATIONS (15)
  // ============================================================
  { id: 'attention-is-all', title: 'Attention Is All You Need', authors: 'Vaswani et al.', year: '2017', url: 'https://arxiv.org/abs/1706.03762', category: 'ai-foundations', type: 'research',
    usedIn: 'أساس نماذج LLM المستخدمة',
    note: 'الورقة المؤسسة لمعمارية المحوّلات.' },
  { id: 'resnet', title: 'Deep Residual Learning for Image Recognition', authors: 'He et al.', year: '2016', url: 'https://arxiv.org/abs/1512.03385', category: 'ai-foundations', type: 'research',
    usedIn: 'العمود الفقري لنماذج الرؤية',
    note: 'شبكات ResNet المعمارية.' },
  { id: 'bert', title: 'BERT — Pre-training of Deep Bidirectional Transformers', authors: 'Devlin et al.', year: '2018', url: 'https://arxiv.org/abs/1810.04805', category: 'ai-foundations', type: 'research',
    usedIn: 'تمثيل النص في تصنيف الأسئلة',
    note: 'أساس فهم النص الحديث.' },
  { id: 'arabic-bert', title: 'AraBERT — Pre-trained Arabic BERT', authors: 'Antoun et al.', year: '2020', url: 'https://arxiv.org/abs/2003.00104', category: 'ai-foundations', type: 'model',
    usedIn: 'تحليل النصوص العربية',
    note: 'نموذج BERT للعربية.' },
  { id: 'clip', title: 'CLIP — Learning Transferable Visual Models From Natural Language', authors: 'Radford et al.', year: '2021', url: 'https://arxiv.org/abs/2103.00020', category: 'ai-foundations', type: 'model',
    usedIn: 'مطابقة الصور بالنص',
    note: 'نموذج صورة–نص متعدد الوسائط.' },
  { id: 'sam', title: 'SAM — Segment Anything', authors: 'Kirillov et al. / Meta', year: '2023', url: 'https://arxiv.org/abs/2304.02643', category: 'ai-foundations', type: 'model',
    usedIn: 'تجزئة الأشياء في الصور',
    note: 'تجزئة عامة لأي كائن في الصورة.' },
  { id: 'dino', title: 'DINOv2 — Self-supervised Vision Features', authors: 'Oquab et al. / Meta', year: '2023', url: 'https://arxiv.org/abs/2304.07193', category: 'ai-foundations', type: 'model',
    usedIn: 'استخراج ملامح الصور',
    note: 'تمثيلات بصرية ذاتية الإشراف.' },
  { id: 'efficientnet', title: 'EfficientNet', authors: 'Tan & Le', year: '2019', url: 'https://arxiv.org/abs/1905.11946', category: 'ai-foundations', type: 'model',
    usedIn: 'بدائل خفيفة للنماذج البصرية',
    note: 'شبكات بصرية متوازنة الحجم/الدقة.' },
  { id: 'mobilenet', title: 'MobileNet V3', authors: 'Howard et al.', year: '2019', url: 'https://arxiv.org/abs/1905.02244', category: 'ai-foundations', type: 'model',
    usedIn: 'تشغيل على الأجهزة المحمولة',
    note: 'نماذج خفيفة للهواتف.' },
  { id: 'tfjs', title: 'TensorFlow.js', authors: 'Google', year: '2024', url: 'https://www.tensorflow.org/js', category: 'ai-foundations', type: 'tool',
    usedIn: 'تشغيل النماذج داخل المتصفّح',
    note: 'منصة ML داخل JavaScript.' },
  { id: 'pytorch', title: 'PyTorch', authors: 'Paszke et al.', year: '2019', url: 'https://pytorch.org/', category: 'ai-foundations', type: 'tool',
    usedIn: 'تدريب النماذج المرجعية',
    note: 'إطار التعلم العميق الأشهر بحثياً.' },
  { id: 'gpt4', title: 'GPT-4 Technical Report', authors: 'OpenAI', year: '2023', url: 'https://arxiv.org/abs/2303.08774', category: 'ai-foundations', type: 'research',
    usedIn: 'تحليلات وتقارير المنصة الذكية',
    note: 'نموذج اللغة الكبير المعتمد للتحليل النصي.' },
  { id: 'gemini', title: 'Gemini Technical Report', authors: 'Google DeepMind', year: '2024', url: 'https://arxiv.org/abs/2312.11805', category: 'ai-foundations', type: 'research',
    usedIn: 'بديل قابل للاستخدام عند الحاجة',
    note: 'نموذج متعدد الوسائط من غوغل.' },
  { id: 'llama', title: 'LLaMA 3 — Open Foundation Models', authors: 'Meta AI', year: '2024', url: 'https://ai.meta.com/llama/', category: 'ai-foundations', type: 'model',
    usedIn: 'نموذج مفتوح للاستضافة الذاتية',
    note: 'نماذج مفتوحة عالية الجودة.' },
  { id: 'shap-lundberg', title: 'SHAP — A Unified Approach to Interpreting Model Predictions', authors: 'Lundberg & Lee', year: '2017', url: 'https://arxiv.org/abs/1705.07874', category: 'ai-foundations', type: 'research',
    usedIn: 'تفسير التوصيات في تقارير التوحّد/ADHD',
    note: 'تفسير قرارات النماذج بشكل عادل.' },

  // ============================================================
  // EXTENDED PACK (+100) — قواميس إشارة، طب، تدريب AI، وصول
  // ============================================================

  // ---- Sign language dictionaries & datasets (20) ----
  { id: 'ext-spreadthesign', title: 'Spread the Sign — قاموس إشارة عالمي', authors: 'European Sign Language Centre', year: '2024', url: 'https://www.spreadthesign.com/', category: 'sign-language', type: 'tool', usedIn: 'مرجع مفردات مترجم لغة الإشارة', note: 'أكبر قاموس فيديو متعدد اللغات للإشارة، يغطي 40+ لغة إشارة.' },
  { id: 'ext-signingsavvy', title: 'Signing Savvy — ASL Video Dictionary', authors: 'Signing Savvy LLC', year: '2024', url: 'https://www.signingsavvy.com/', category: 'sign-language', type: 'tool', usedIn: 'مفردات ASL في قاعدة المترجم', note: 'قاموس فيديو ASL عالي الجودة.' },
  { id: 'ext-handspeak', title: 'Handspeak — ASL Dictionary & Lessons', authors: 'Handspeak', year: '2024', url: 'https://www.handspeak.com/', category: 'sign-language', type: 'tool', usedIn: 'دروس مدمجة في قسم Sign Language', note: 'موارد تعليم ASL وقاموس فيديو.' },
  { id: 'ext-lifeprint', title: 'Lifeprint ASL Dictionary (Bill Vicars)', authors: 'Dr. Bill Vicars', year: '2024', url: 'https://www.lifeprint.com/', category: 'sign-language', type: 'tool', usedIn: 'تحقق من شكل الإشارة في handshapes', note: 'مرجع تعليمي شامل لـ ASL.' },
  { id: 'ext-bsl-signbank', title: 'BSL SignBank — University College London', authors: 'DCAL Research Centre, UCL', year: '2024', url: 'https://bslsignbank.ucl.ac.uk/', category: 'sign-language', type: 'dataset', usedIn: 'مفردات لغة الإشارة البريطانية', note: 'قاعدة بيانات أكاديمية للغة الإشارة البريطانية BSL.' },
  { id: 'ext-auslan-signbank', title: 'Auslan SignBank', authors: 'Trevor Johnston et al.', year: '2024', url: 'https://auslan.org.au/', category: 'sign-language', type: 'dataset', usedIn: 'مفردات Auslan (لغة إشارة أسترالية)', note: 'قاموس Auslan الموثّق أكاديمياً.' },
  { id: 'ext-dgs-korpus', title: 'DGS-Korpus — German Sign Language Corpus', authors: 'University of Hamburg', year: '2024', url: 'https://www.sign-lang.uni-hamburg.de/dgs-korpus/', category: 'sign-language', type: 'dataset', usedIn: 'بيانات لغة الإشارة الألمانية DGS', note: 'كوربس فيديو وأنوتيشن DGS الأكاديمي.' },
  { id: 'ext-elix-lsf', title: 'Elix — Dictionnaire LSF', authors: 'Elix', year: '2024', url: 'https://dico.elix-lsf.fr/', category: 'sign-language', type: 'tool', usedIn: 'مفردات لغة الإشارة الفرنسية LSF', note: 'قاموس فيديو فرنسي ↔ LSF.' },
  { id: 'ext-sematos', title: 'Sématos — Multilingual Sign Dictionary', authors: 'Sématos', year: '2024', url: 'https://www.sematos.eu/', category: 'sign-language', type: 'tool', usedIn: 'مرجع متعدد لغات الإشارة الأوروبية', note: 'قاموس فيديو يجمع عدة لغات إشارة.' },
  { id: 'ext-ngt-gebaren', title: 'Nederlands Gebarencentrum — NGT', authors: 'Nederlands Gebarencentrum', year: '2024', url: 'https://www.gebarencentrum.nl/', category: 'sign-language', type: 'tool', usedIn: 'مفردات لغة الإشارة الهولندية', note: 'مرجع رسمي للغة الإشارة الهولندية NGT.' },
  { id: 'ext-wfd', title: 'World Federation of the Deaf', authors: 'WFD', year: '2024', url: 'https://wfdeaf.org/', category: 'sign-language', type: 'guideline', usedIn: 'سياسات حقوق الصم في قسم Sign', note: 'الاتحاد العالمي للصم — معايير حقوقية وتعليمية.' },
  { id: 'ext-wlasl', title: 'WLASL — Word-Level American Sign Language Dataset', authors: 'Li et al.', year: '2020', url: 'https://dxli94.github.io/WLASL/', category: 'sign-language', type: 'dataset', usedIn: 'تدريب نموذج التعرّف على إشارات ASL', note: 'أكبر داتاسيت فيديو لإشارات ASL على مستوى الكلمة.' },
  { id: 'ext-phoenix14t', title: 'RWTH-PHOENIX-Weather 2014T', authors: 'Koller et al., RWTH Aachen', year: '2018', url: 'https://www-i6.informatik.rwth-aachen.de/~koller/RWTH-PHOENIX-2014-T/', category: 'sign-language', type: 'dataset', usedIn: 'تقييم ترجمة فيديو إشارة → نص', note: 'المعيار الأكاديمي الأشهر لترجمة DGS.' },
  { id: 'ext-how2sign', title: 'How2Sign — Multimodal Continuous American Sign Language', authors: 'Duarte et al.', year: '2021', url: 'https://how2sign.github.io/', category: 'sign-language', type: 'dataset', usedIn: 'تدريب نماذج إشارة مستمرة', note: 'داتاسيت متعدد الوسائط لإشارات ASL متواصلة.' },
  { id: 'ext-ms-asl', title: 'MS-ASL — Microsoft American Sign Language Dataset', authors: 'Microsoft Research', year: '2019', url: 'https://www.microsoft.com/en-us/research/project/ms-asl/', category: 'sign-language', type: 'dataset', usedIn: 'تدريب التعرّف على إشارات ASL', note: '1000 إشارة ASL بفيديوهات حقيقية.' },
  { id: 'ext-signall', title: 'SignAll — Sign Language Recognition Platform', authors: 'SignAll Technologies', year: '2024', url: 'https://www.signall.us/', category: 'sign-language', type: 'tool', usedIn: 'مرجع لمسارات التعرّف الآلي على الإشارة', note: 'منصة تجارية متخصصة بترجمة ASL آلياً.' },
  { id: 'ext-karsl', title: 'KArSL — King Saud University Arabic Sign Language Dataset', authors: 'Sidig, Luqman, Mahmoud, Mohandes', year: '2021', url: 'https://hamzah-luqman.github.io/KArSL/', category: 'sign-language', type: 'dataset', usedIn: 'تدريب التعرّف على لغة الإشارة العربية', note: 'أكبر داتاسيت أكاديمي للغة الإشارة العربية.' },
  { id: 'ext-arsl2018', title: 'ArSL2018 — Arabic Alphabets Sign Language Dataset', authors: 'Latif, Mohammad et al.', year: '2019', url: 'https://data.mendeley.com/datasets/y7pckrw6z2/1', category: 'sign-language', type: 'dataset', usedIn: 'تعرّف على الحروف الأبجدية بالإشارة العربية', note: '54K صورة لحروف الإشارة العربية.' },
  { id: 'ext-lasign-arab', title: 'القاموس الإشاري العربي الموحّد — الأمانة العامة لاتحاد الصم العرب', authors: 'الاتحاد العربي للهيئات العاملة في رعاية الصم', year: '2022', url: 'https://www.lasarab.org/', category: 'sign-language', type: 'standard', usedIn: 'مرجع المفردات الموحّدة بالعربية', note: 'قاموس إشاري عربي معتمد لتوحيد المفردات.' },
  { id: 'ext-signbank-org', title: 'SignBank — Sign Language Database', authors: 'SignBank.org', year: '2024', url: 'https://www.signbank.org/', category: 'sign-language', type: 'tool', usedIn: 'مرجع مكتبة إشارات', note: 'قاعدة بيانات مفتوحة للإشارات.' },

  // ---- Medical & clinical sources (25) ----
  { id: 'ext-uptodate', title: 'UpToDate — Evidence-Based Clinical Decision Support', authors: 'Wolters Kluwer', year: '2024', url: 'https://www.uptodate.com/', category: 'clinical-ai', type: 'guideline', usedIn: 'مرجع قرار سريري في مختبر المحاكاة', note: 'الأشهر عالمياً للقرار السريري المبني على الأدلة.' },
  { id: 'ext-bmj-best', title: 'BMJ Best Practice', authors: 'BMJ Publishing Group', year: '2024', url: 'https://bestpractice.bmj.com/', category: 'clinical-ai', type: 'guideline', usedIn: 'بروتوكولات الحالات السريرية', note: 'إرشادات سريرية محدّثة لمئات الحالات.' },
  { id: 'ext-cochrane', title: 'Cochrane Library — Systematic Reviews', authors: 'Cochrane Collaboration', year: '2024', url: 'https://www.cochranelibrary.com/', category: 'clinical-ai', type: 'research', usedIn: 'مراجعات منهجية تدعم المحتوى الطبي', note: 'المرجع الذهبي للمراجعات المنهجية الطبية.' },
  { id: 'ext-pubmed', title: 'PubMed — NCBI / NLM', authors: 'U.S. National Library of Medicine', year: '2024', url: 'https://pubmed.ncbi.nlm.nih.gov/', category: 'clinical-ai', type: 'tool', usedIn: 'بحث الأدلة في كل مكوّن طبي', note: 'محرّك بحث الأبحاث الطبية الحيوية الأكبر عالمياً.' },
  { id: 'ext-medlineplus', title: 'MedlinePlus — Trusted Health Information', authors: 'U.S. NLM / NIH', year: '2024', url: 'https://medlineplus.gov/', category: 'clinical-ai', type: 'guideline', usedIn: 'شروحات صحية موجّهة لذوي الإعاقة', note: 'محتوى صحي للمستهلك من NIH.' },
  { id: 'ext-mayo', title: 'Mayo Clinic — Diseases & Conditions', authors: 'Mayo Foundation', year: '2024', url: 'https://www.mayoclinic.org/diseases-conditions', category: 'clinical-ai', type: 'guideline', usedIn: 'شروحات الحالات السريرية', note: 'مرجع موثوق لتعريف الحالات وإدارتها.' },
  { id: 'ext-cleveland', title: 'Cleveland Clinic — Health Library', authors: 'Cleveland Clinic', year: '2024', url: 'https://my.clevelandclinic.org/health', category: 'clinical-ai', type: 'guideline', usedIn: 'مرجع تثقيف صحي مساند', note: 'مكتبة صحية شاملة.' },
  { id: 'ext-who-icd11', title: 'WHO ICD-11 — International Classification of Diseases', authors: 'World Health Organization', year: '2024', url: 'https://icd.who.int/', category: 'clinical-ai', type: 'standard', usedIn: 'تصنيف الحالات في التقارير السريرية', note: 'النسخة 11 من التصنيف الدولي للأمراض.' },
  { id: 'ext-icd11-mms', title: 'ICD-11 MMS — Browser', authors: 'WHO', year: '2024', url: 'https://icd.who.int/browse11', category: 'clinical-ai', type: 'standard', usedIn: 'بحث رموز ICD-11', note: 'متصفح رسمي لـ ICD-11.' },
  { id: 'ext-snomed', title: 'SNOMED CT — Clinical Terminology', authors: 'SNOMED International', year: '2024', url: 'https://www.snomed.org/', category: 'clinical-ai', type: 'standard', usedIn: 'ترميز المفاهيم السريرية', note: 'أشمل قاموس مصطلحات سريرية عالمياً.' },
  { id: 'ext-loinc', title: 'LOINC — Logical Observation Identifiers Names and Codes', authors: 'Regenstrief Institute', year: '2024', url: 'https://loinc.org/', category: 'clinical-ai', type: 'standard', usedIn: 'رموز الفحوصات المخبرية', note: 'المعيار العالمي لتسمية الفحوصات.' },
  { id: 'ext-rxnorm', title: 'RxNorm — Normalized Drug Names', authors: 'U.S. NLM', year: '2024', url: 'https://www.nlm.nih.gov/research/umls/rxnorm/', category: 'clinical-ai', type: 'standard', usedIn: 'توحيد أسماء الأدوية', note: 'قاموس موحّد لأسماء الأدوية.' },
  { id: 'ext-aha-cpr', title: 'AHA Guidelines for CPR & ECC 2020', authors: 'American Heart Association', year: '2020', url: 'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines', category: 'clinical-ai', type: 'guideline', usedIn: 'بروتوكولات الإنعاش في المختبر السريري', note: 'إرشادات AHA للإنعاش القلبي الرئوي.' },
  { id: 'ext-erc-2021', title: 'ERC Resuscitation Guidelines 2021', authors: 'European Resuscitation Council', year: '2021', url: 'https://www.erc.edu/guidelines', category: 'clinical-ai', type: 'guideline', usedIn: 'بروتوكول أوروبي بديل للإنعاش', note: 'الإرشادات الأوروبية المعتمدة للإنعاش.' },
  { id: 'ext-mhgap', title: 'WHO mhGAP Intervention Guide', authors: 'World Health Organization', year: '2023', url: 'https://www.who.int/teams/mental-health-and-substance-use/treatment-care/mental-health-gap-action-programme', category: 'clinical-ai', type: 'guideline', usedIn: 'تدخّلات الصحة النفسية في بيئات قليلة الموارد', note: 'بروتوكولات WHO للصحة النفسية.' },
  { id: 'ext-redcross-fa', title: 'American Red Cross — First Aid Training', authors: 'American Red Cross', year: '2024', url: 'https://www.redcross.org/take-a-class/first-aid', category: 'clinical-ai', type: 'guideline', usedIn: 'مراجع الإسعافات الأولية', note: 'مناهج معتمدة للإسعافات الأولية.' },
  { id: 'ext-sja-fa', title: 'St John Ambulance — First Aid Advice', authors: 'St John Ambulance UK', year: '2024', url: 'https://www.sja.org.uk/get-advice/first-aid-advice/', category: 'clinical-ai', type: 'guideline', usedIn: 'بطاقات الإسعاف الأولي', note: 'دليل بريطاني تفصيلي للإسعافات الأولية.' },
  { id: 'ext-apa-assess', title: 'APA — DSM-5 Online Assessment Measures', authors: 'American Psychiatric Association', year: '2024', url: 'https://www.psychiatry.org/psychiatrists/practice/dsm/educational-resources/assessment-measures', category: 'autism-diagnosis', type: 'tool', usedIn: 'مقاييس DSM المعتمدة', note: 'أدوات تقييم DSM-5 الرسمية للتنزيل.' },
  { id: 'ext-umls', title: 'UMLS — Unified Medical Language System', authors: 'U.S. NLM', year: '2024', url: 'https://www.nlm.nih.gov/research/umls/index.html', category: 'clinical-ai', type: 'standard', usedIn: 'ربط المصطلحات الطبية متعددة المصادر', note: 'منظومة موحّدة للمصطلحات الطبية.' },
  { id: 'ext-openfda', title: 'openFDA — Drug & Device API', authors: 'U.S. FDA', year: '2024', url: 'https://open.fda.gov/', category: 'clinical-ai', type: 'tool', usedIn: 'تنبيهات الأدوية والآثار الجانبية', note: 'API رسمي لبيانات FDA.' },
  { id: 'ext-drugbank', title: 'DrugBank — Drug Database', authors: 'OMx Personal Health Analytics', year: '2024', url: 'https://go.drugbank.com/', category: 'clinical-ai', type: 'dataset', usedIn: 'تفاعلات الأدوية في الجلسات السريرية', note: 'قاعدة بيانات شاملة للأدوية والتفاعلات.' },
  { id: 'ext-ctgov', title: 'ClinicalTrials.gov', authors: 'U.S. NIH', year: '2024', url: 'https://clinicaltrials.gov/', category: 'clinical-ai', type: 'tool', usedIn: 'متابعة التجارب السريرية المرجعية', note: 'سجل عالمي للتجارب السريرية.' },
  { id: 'ext-who-disability', title: 'WHO — Disability', authors: 'World Health Organization', year: '2024', url: 'https://www.who.int/health-topics/disability', category: 'inclusive-edu', type: 'guideline', usedIn: 'إطار حقوق وصحة الأشخاص ذوي الإعاقة', note: 'مرجع WHO الرسمي للإعاقة.' },
  { id: 'ext-idea', title: 'IDEA — Individuals with Disabilities Education Act', authors: 'U.S. Department of Education', year: '2024', url: 'https://sites.ed.gov/idea/', category: 'inclusive-edu', type: 'standard', usedIn: 'إطار IEP والخطط التربوية', note: 'القانون الفيدرالي الأميركي لتعليم ذوي الإعاقة.' },
  { id: 'ext-who-icfcy', title: 'WHO ICF-CY — Children & Youth Version', authors: 'World Health Organization', year: '2007', url: 'https://www.who.int/standards/classifications/international-classification-of-functioning-disability-and-health', category: 'inclusive-edu', type: 'standard', usedIn: 'إطار تصنيف الأداء الوظيفي', note: 'تصنيف WHO للأداء والإعاقة والصحة.' },

  // ---- AI training frameworks, datasets, papers (30) ----
  { id: 'ext-pytorch', title: 'PyTorch', authors: 'PyTorch Foundation / Meta AI', year: '2024', url: 'https://pytorch.org/', category: 'ai-foundations', type: 'tool', usedIn: 'تدريب نماذج الرؤية واللغة', note: 'إطار التعلم العميق الأساسي.' },
  { id: 'ext-tf', title: 'TensorFlow', authors: 'Google Brain', year: '2024', url: 'https://www.tensorflow.org/', category: 'ai-foundations', type: 'tool', usedIn: 'تدريب نماذج بديلة وتحويلها', note: 'إطار تعلم آلي مفتوح المصدر.' },
  { id: 'ext-keras', title: 'Keras 3', authors: 'François Chollet et al.', year: '2024', url: 'https://keras.io/', category: 'ai-foundations', type: 'tool', usedIn: 'بناء نماذج تجريبية سريعة', note: 'واجهة عليا للتعلم العميق.' },
  { id: 'ext-jax', title: 'JAX — Composable transformations of Python+NumPy', authors: 'Google Research', year: '2024', url: 'https://jax.readthedocs.io/', category: 'ai-foundations', type: 'tool', usedIn: 'تجارب التدريب عالي الأداء', note: 'حساب رمزي مع تسارع GPU/TPU.' },
  { id: 'ext-hf-transformers', title: 'Hugging Face Transformers', authors: 'Wolf et al.', year: '2024', url: 'https://huggingface.co/docs/transformers', category: 'ai-foundations', type: 'tool', usedIn: 'استدعاء نماذج LLM/Vision', note: 'مكتبة النماذج اللغوية الأشهر.' },
  { id: 'ext-hf-datasets', title: 'Hugging Face Datasets', authors: 'Hugging Face', year: '2024', url: 'https://huggingface.co/docs/datasets', category: 'ai-foundations', type: 'tool', usedIn: 'تحميل بيانات التدريب', note: 'مكتبة بيانات موحّدة وفعّالة.' },
  { id: 'ext-sklearn', title: 'scikit-learn', authors: 'Pedregosa et al.', year: '2024', url: 'https://scikit-learn.org/', category: 'ai-foundations', type: 'tool', usedIn: 'نماذج تصنيف وتنقية بيانات', note: 'مكتبة ML الكلاسيكية.' },
  { id: 'ext-xgboost', title: 'XGBoost', authors: 'Chen & Guestrin', year: '2016', url: 'https://xgboost.readthedocs.io/', category: 'ai-foundations', type: 'tool', usedIn: 'تحسين قرارات التصنيف الجدولي', note: 'تعزيز التدرّج عالي الأداء.' },
  { id: 'ext-lightgbm', title: 'LightGBM', authors: 'Microsoft Research', year: '2017', url: 'https://lightgbm.readthedocs.io/', category: 'ai-foundations', type: 'tool', usedIn: 'تعزيز سريع للبيانات الكبيرة', note: 'إطار GBDT خفيف وسريع.' },
  { id: 'ext-onnx', title: 'ONNX — Open Neural Network Exchange', authors: 'LF AI & Data', year: '2024', url: 'https://onnx.ai/', category: 'ai-foundations', type: 'standard', usedIn: 'نقل النماذج بين الأطر', note: 'صيغة موحّدة لنماذج التعلم العميق.' },
  { id: 'ext-onnxrt', title: 'ONNX Runtime', authors: 'Microsoft', year: '2024', url: 'https://onnxruntime.ai/', category: 'ai-foundations', type: 'tool', usedIn: 'تشغيل النماذج على الجهاز/الخادم', note: 'محرك استدلال عالي الأداء.' },
  { id: 'ext-cuda', title: 'NVIDIA CUDA Toolkit', authors: 'NVIDIA', year: '2024', url: 'https://developer.nvidia.com/cuda-toolkit', category: 'ai-foundations', type: 'tool', usedIn: 'تسريع التدريب على GPU', note: 'منظومة CUDA الرسمية.' },
  { id: 'ext-cudnn', title: 'NVIDIA cuDNN', authors: 'NVIDIA', year: '2024', url: 'https://developer.nvidia.com/cudnn', category: 'ai-foundations', type: 'tool', usedIn: 'تسريع DL primitives على GPU', note: 'مكتبة بدائيات الشبكات العصبية.' },
  { id: 'ext-wandb', title: 'Weights & Biases', authors: 'W&B Inc.', year: '2024', url: 'https://wandb.ai/', category: 'ai-foundations', type: 'tool', usedIn: 'تتبّع تجارب التدريب', note: 'منصة MLOps لتتبّع التجارب.' },
  { id: 'ext-mlflow', title: 'MLflow', authors: 'Databricks', year: '2024', url: 'https://mlflow.org/', category: 'ai-foundations', type: 'tool', usedIn: 'إدارة دورة حياة نماذج ML', note: 'منصة MLOps مفتوحة.' },
  { id: 'ext-ray', title: 'Ray — Distributed AI Framework', authors: 'Anyscale / UC Berkeley RISELab', year: '2024', url: 'https://www.ray.io/', category: 'ai-foundations', type: 'tool', usedIn: 'تدريب موزّع وضبط المعاملات', note: 'إطار حوسبة موزّعة لتدريب AI.' },
  { id: 'ext-dvc', title: 'DVC — Data Version Control', authors: 'Iterative.ai', year: '2024', url: 'https://dvc.org/', category: 'ai-foundations', type: 'tool', usedIn: 'إصدار بيانات ونماذج التدريب', note: 'Git-like للبيانات والنماذج.' },
  { id: 'ext-labelstudio', title: 'Label Studio', authors: 'HumanSignal', year: '2024', url: 'https://labelstud.io/', category: 'ai-foundations', type: 'tool', usedIn: 'تعليم البيانات للتدريب', note: 'منصة تعليم بيانات مفتوحة.' },
  { id: 'ext-roboflow', title: 'Roboflow — Computer Vision Platform', authors: 'Roboflow Inc.', year: '2024', url: 'https://roboflow.com/', category: 'ai-foundations', type: 'tool', usedIn: 'تجهيز بيانات الرؤية الحاسوبية', note: 'أدوات بيانات CV شاملة.' },
  { id: 'ext-langchain', title: 'LangChain', authors: 'LangChain Inc.', year: '2024', url: 'https://www.langchain.com/', category: 'ai-foundations', type: 'tool', usedIn: 'تنسيق وكلاء LLM في المرشد', note: 'إطار بناء تطبيقات LLM.' },
  { id: 'ext-llamaindex', title: 'LlamaIndex', authors: 'Jerry Liu et al.', year: '2024', url: 'https://www.llamaindex.ai/', category: 'ai-foundations', type: 'tool', usedIn: 'RAG على مصادر منصة دامج', note: 'فهرسة وبحث RAG.' },
  { id: 'ext-pinecone', title: 'Pinecone — Vector Database', authors: 'Pinecone Systems', year: '2024', url: 'https://www.pinecone.io/docs/', category: 'ai-foundations', type: 'tool', usedIn: 'تخزين متجهات المعرفة', note: 'قاعدة بيانات متجهية مُدارة.' },
  { id: 'ext-weaviate', title: 'Weaviate — Open Vector DB', authors: 'Weaviate B.V.', year: '2024', url: 'https://weaviate.io/developers/weaviate', category: 'ai-foundations', type: 'tool', usedIn: 'بديل مفتوح للتخزين المتجهي', note: 'قاعدة بيانات متجهية مفتوحة.' },
  { id: 'ext-chroma', title: 'ChromaDB', authors: 'Chroma', year: '2024', url: 'https://docs.trychroma.com/', category: 'ai-foundations', type: 'tool', usedIn: 'تخزين embeddings محلياً', note: 'قاعدة متجهية خفيفة.' },
  { id: 'ext-faiss', title: 'FAISS — Similarity Search', authors: 'Meta AI Research', year: '2024', url: 'https://github.com/facebookresearch/faiss', category: 'ai-foundations', type: 'tool', usedIn: 'بحث متجهي عالي السرعة', note: 'مكتبة بحث تشابه عالية الأداء.' },
  { id: 'ext-lora', title: 'LoRA — Low-Rank Adaptation of LLMs', authors: 'Hu et al.', year: '2021', url: 'https://arxiv.org/abs/2106.09685', category: 'ai-foundations', type: 'research', usedIn: 'ضبط دقيق فعّال للنماذج', note: 'تقنية fine-tuning منخفضة الكلفة.' },
  { id: 'ext-attention', title: 'Attention Is All You Need', authors: 'Vaswani et al.', year: '2017', url: 'https://arxiv.org/abs/1706.03762', category: 'ai-foundations', type: 'research', usedIn: 'أساس بنية Transformer للنماذج', note: 'الورقة المؤسِّسة للمحوّلات.' },
  { id: 'ext-bert', title: 'BERT — Pre-training of Deep Bidirectional Transformers', authors: 'Devlin et al.', year: '2018', url: 'https://arxiv.org/abs/1810.04805', category: 'ai-foundations', type: 'research', usedIn: 'تمثيلات نصية للبحث الدلالي', note: 'نموذج تمثيل لغوي ثنائي الاتجاه.' },
  { id: 'ext-resnet', title: 'Deep Residual Learning for Image Recognition (ResNet)', authors: 'He et al.', year: '2015', url: 'https://arxiv.org/abs/1512.03385', category: 'ai-foundations', type: 'research', usedIn: 'أساس شبكات الرؤية', note: 'ResNet وأهمية الوصلات المتبقية.' },
  { id: 'ext-imagenet', title: 'ImageNet', authors: 'Deng, Fei-Fei et al.', year: '2009', url: 'https://www.image-net.org/', category: 'ai-foundations', type: 'dataset', usedIn: 'أوزان مسبقة التدريب للرؤية', note: 'المعيار الأكاديمي لتدريب CV.' },
  { id: 'ext-coco', title: 'COCO — Common Objects in Context', authors: 'Lin et al.', year: '2014', url: 'https://cocodataset.org/', category: 'ai-foundations', type: 'dataset', usedIn: 'كشف الأجسام والتجزئة', note: 'داتاسيت كشف وتجزئة شامل.' },
  { id: 'ext-mediapipe', title: 'Google MediaPipe', authors: 'Google', year: '2024', url: 'https://developers.google.com/mediapipe', category: 'ai-foundations', type: 'tool', usedIn: 'تتبّع اليد للإشارة + Pose للحركة', note: 'إطار ML on-device للرؤية.' },
  { id: 'ext-opencv', title: 'OpenCV', authors: 'OpenCV Team', year: '2024', url: 'https://opencv.org/', category: 'ai-foundations', type: 'tool', usedIn: 'معالجة الكاميرا والصور', note: 'مكتبة الرؤية الحاسوبية المعيارية.' },

  // ---- Speech / TTS / STT (10) ----
  { id: 'ext-whisper', title: 'OpenAI Whisper — Robust ASR', authors: 'Radford et al., OpenAI', year: '2022', url: 'https://github.com/openai/whisper', category: 'speech-audio', type: 'model', usedIn: 'تحويل صوت → نص متعدد اللغات', note: 'نموذج ASR متعدد اللغات (99+).' },
  { id: 'ext-commonvoice', title: 'Mozilla Common Voice', authors: 'Mozilla Foundation', year: '2024', url: 'https://commonvoice.mozilla.org/', category: 'speech-audio', type: 'dataset', usedIn: 'تدريب/تقييم STT لـ 120+ لغة', note: 'أكبر داتاسيت صوت متعدد اللغات مفتوح.' },
  { id: 'ext-librispeech', title: 'LibriSpeech ASR Corpus', authors: 'Panayotov et al.', year: '2015', url: 'https://www.openslr.org/12', category: 'speech-audio', type: 'dataset', usedIn: 'تقييم نماذج ASR الإنجليزية', note: '1000 ساعة كلام مقروء.' },
  { id: 'ext-espnet', title: 'ESPnet — End-to-End Speech Toolkit', authors: 'Watanabe et al.', year: '2024', url: 'https://espnet.github.io/espnet/', category: 'speech-audio', type: 'tool', usedIn: 'تدريب نماذج ASR/TTS', note: 'مجموعة أدوات شاملة للكلام.' },
  { id: 'ext-kaldi', title: 'Kaldi Speech Recognition Toolkit', authors: 'Povey et al.', year: '2024', url: 'https://kaldi-asr.org/', category: 'speech-audio', type: 'tool', usedIn: 'بدائل ASR كلاسيكية للمقارنة', note: 'إطار ASR كلاسيكي عالي الجودة.' },
  { id: 'ext-coqui-tts', title: 'Coqui TTS', authors: 'Coqui', year: '2024', url: 'https://github.com/coqui-ai/TTS', category: 'speech-audio', type: 'tool', usedIn: 'TTS مفتوح بديل', note: 'مكتبة TTS مفتوحة المصدر.' },
  { id: 'ext-webspeech', title: 'W3C Web Speech API', authors: 'W3C', year: '2024', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API', category: 'speech-audio', type: 'standard', usedIn: 'STT/TTS داخل المتصفح', note: 'واجهة برمجة كلام معيارية في الويب.' },
  { id: 'ext-ssml', title: 'W3C SSML 1.1', authors: 'W3C', year: '2010', url: 'https://www.w3.org/TR/speech-synthesis11/', category: 'speech-audio', type: 'standard', usedIn: 'تحسين نطق النصوص العربية/المتعددة', note: 'لغة وسم تركيب الكلام.' },
  { id: 'ext-tonejs', title: 'Tone.js — Web Audio Framework', authors: 'Yotam Mann', year: '2024', url: 'https://tonejs.github.io/', category: 'speech-audio', type: 'tool', usedIn: 'الإخراج الصوتي للجسر الحسّي', note: 'إطار صوت متقدّم لويب.' },
  { id: 'ext-webaudio', title: 'W3C Web Audio API', authors: 'W3C', year: '2024', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API', category: 'speech-audio', type: 'standard', usedIn: 'معالجة الصوت في المتصفح', note: 'واجهة برمجة الصوت في الويب.' },

  // ---- Accessibility, inclusive ed, standards (15) ----
  { id: 'ext-wcag22', title: 'WCAG 2.2 — Web Content Accessibility Guidelines', authors: 'W3C WAI', year: '2023', url: 'https://www.w3.org/TR/WCAG22/', category: 'inclusive-edu', type: 'standard', usedIn: 'معايير وصول واجهة دامج', note: 'المعيار العالمي لإتاحة الويب.' },
  { id: 'ext-aria12', title: 'WAI-ARIA 1.2', authors: 'W3C WAI', year: '2023', url: 'https://www.w3.org/TR/wai-aria-1.2/', category: 'inclusive-edu', type: 'standard', usedIn: 'سمات ARIA في مكوّنات shadcn/Radix', note: 'مواصفات الإتاحة الديناميكية.' },
  { id: 'ext-atag2', title: 'ATAG 2.0 — Authoring Tool Accessibility', authors: 'W3C WAI', year: '2015', url: 'https://www.w3.org/TR/ATAG20/', category: 'inclusive-edu', type: 'standard', usedIn: 'إتاحة أدوات إنشاء المحتوى داخل دامج', note: 'معيار إتاحة أدوات التأليف.' },
  { id: 'ext-unesco-incl', title: 'UNESCO — Inclusive Education', authors: 'UNESCO', year: '2024', url: 'https://www.unesco.org/en/inclusive-education', category: 'inclusive-edu', type: 'guideline', usedIn: 'إطار سياسات التعليم الدامج', note: 'إطار سياسات اليونسكو للدمج.' },
  { id: 'ext-uncrpd', title: 'UN CRPD — Convention on the Rights of Persons with Disabilities', authors: 'United Nations', year: '2006', url: 'https://www.un.org/development/desa/disabilities/convention-on-the-rights-of-persons-with-disabilities.html', category: 'inclusive-edu', type: 'standard', usedIn: 'إطار حقوق المستخدمين', note: 'الاتفاقية الأممية لحقوق ذوي الإعاقة.' },
  { id: 'ext-udl', title: 'UDL Guidelines — Universal Design for Learning', authors: 'CAST', year: '2024', url: 'https://udlguidelines.cast.org/', category: 'inclusive-edu', type: 'guideline', usedIn: 'تصميم محتوى متعدد التمثيل', note: 'إطار التصميم العالمي للتعلم.' },
  { id: 'ext-section508', title: 'Section 508 — U.S. Accessibility Standards', authors: 'U.S. GSA', year: '2024', url: 'https://www.section508.gov/', category: 'inclusive-edu', type: 'standard', usedIn: 'توافق إتاحة فيدرالي أميركي', note: 'متطلبات الإتاحة في المؤسسات الأميركية.' },
  { id: 'ext-en301549', title: 'EN 301 549 — European Accessibility Standard', authors: 'ETSI/CEN/CENELEC', year: '2021', url: 'https://www.etsi.org/deliver/etsi_en/301500_301599/301549/', category: 'inclusive-edu', type: 'standard', usedIn: 'توافق أوروبي للإتاحة الرقمية', note: 'المعيار الأوروبي لإتاحة ICT.' },
  { id: 'ext-ada-std', title: 'ADA Standards for Accessible Design', authors: 'U.S. DOJ', year: '2010', url: 'https://www.ada.gov/law-and-regs/design-standards/', category: 'inclusive-edu', type: 'standard', usedIn: 'إطار ADA للتطبيقات', note: 'معايير ADA للتصميم المُتاح.' },
  { id: 'ext-webaim-contrast', title: 'WebAIM — Contrast Checker', authors: 'WebAIM', year: '2024', url: 'https://webaim.org/resources/contrastchecker/', category: 'inclusive-edu', type: 'tool', usedIn: 'فحص تباين ألوان واجهة دامج', note: 'أداة فحص تباين معيارية.' },
  { id: 'ext-axe', title: 'axe-core — Accessibility Engine', authors: 'Deque Systems', year: '2024', url: 'https://github.com/dequelabs/axe-core', category: 'inclusive-edu', type: 'tool', usedIn: 'اختبار إتاحة آلي', note: 'محرّك اختبار إتاحة موثوق.' },
  { id: 'ext-lighthouse', title: 'Google Lighthouse', authors: 'Google', year: '2024', url: 'https://developer.chrome.com/docs/lighthouse', category: 'inclusive-edu', type: 'tool', usedIn: 'تدقيق أداء وإتاحة', note: 'تدقيق ويب شامل.' },
  { id: 'ext-unicode-braille', title: 'Unicode Braille Patterns (U+2800–U+28FF)', authors: 'Unicode Consortium', year: '2024', url: 'https://www.unicode.org/charts/PDF/U2800.pdf', category: 'braille', type: 'standard', usedIn: 'ترميز خلايا بريل في القسم', note: 'كتلة يونيكود الرسمية لبريل.' },
  { id: 'ext-liblouis', title: 'Liblouis — Braille Translator', authors: 'Liblouis Project', year: '2024', url: 'https://liblouis.io/', category: 'braille', type: 'tool', usedIn: 'تحويل نص ⟷ بريل لعدة لغات', note: 'مترجم بريل مفتوح المصدر مرجعي.' },
  { id: 'ext-brltty', title: 'BRLTTY — Braille Display Driver', authors: 'BRLTTY Project', year: '2024', url: 'https://brltty.app/', category: 'braille', type: 'tool', usedIn: 'دعم شاشات بريل', note: 'بروتوكولات شاشات بريل القياسية.' },
];

export const SOURCE_COUNT = SOURCES.length;
